### ISSUE TITLE
Server framework question

### ISSUE THREAD

**Issue by Arsakes** [TES3MP/TES3MP#102]
Quick question - do you guys use some framework for server side code? There's a few of them now.

In original open mw is there a clear separation for server and client??

I'm curious what potential there is for implementing larger scale mplayer.

Regards,
P

**Comment by Koncord** [comment]
Hello!
We use RakNet for networking. RakNet works fine up to ~1000 connections. In theory tes3mp can withstand up to 60 connections. We will improve net code later.

**Comment by Koncord** [comment]
The original OpenMW doesn't have multiplayer.

**Comment by Arsakes** [comment]
Thanks!

I know it doesn't have multiplayer - however in same game cases there's a clear separation in code for:
server - an API + set of simulation/logic modules.
client - graphic renderer + input handling,  asks "server" api.
Only they both work on the same machine.

I'm little lost reading FAQ. What I can't understand how it is possible that some things are synchronized and same are not.

Could you tell a little about code architecture? How division for server and client looks like?
What things are still calculated on client-side.
How often do you broadcast the server world state?

I understand you do not have persistance yet and world state is lost after server shutdown.

**Comment by davidcernat** [comment]
You're a coder too, Arsakes. Why not see for yourself?

Here's where most of the client-side code for networking can be found:

https://github.com/TES3MP/openmw-tes3mp/tree/master/apps/openmw/mwmp

Here's where all of the server-side code can be found:

https://github.com/TES3MP/openmw-tes3mp/tree/master/apps/openmw-mp

Here are their shared packets and packet controllers:

https://github.com/TES3MP/openmw-tes3mp/tree/master/components/openmw-mp

There are also places in OpenMW's code that packets are now sent from, mostly relating to world events such as picking up items, dropping them, opening doors and so on. Here's an example of that:

https://github.com/TES3MP/openmw-tes3mp/blob/master/apps/openmw/mwworld/actiontake.cpp#L25

Compare it with the original OpenMW code for that:

https://github.com/OpenMW/openmw/blob/master/apps/openmw/mwworld/actiontake.cpp

Sure, we could write you an essay, but we'd rather just work on new features.

**Comment by Arsakes** [comment]
Thanks David,

I will check it out.
