### ISSUE TITLE
Upon logging in some characters are displayed as the default dunmer

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#11]
Whenever a character logs in there's a somewhat random chance it will be displayed as the default dunmer, regardless of race.

This effect can be negated by making the observer switch cells,

Additional, by removing the clothing of the affected character, [the underneath body parts will be those of the correct race.](https://imgur.com/5UDQ4lp)

[At 33s this video ](https://www.youtube.com/watch?v=9X1OGotlXM8&t=33)displays a recently logged in character being displayed as the default dunmer, followed by the negation of that effect by the observer's cell switching.

**Comment by Koncord** [comment]
Issue with [this](https://github.com/TES3MP/openmw-tes3mp/blob/master/apps/openmw/mwmp/DedicatedPlayer.cpp#L78) fragment of code.
Possible solution:
If record of player has changed, then we should remove and re-create object of player
Or
Just move player into ToddTest, and then back to the desired cell

**Comment by davidcernat** [comment]
Fixed by aa69c156c720ea111ca2dd04f512a4f5b8ee4ed2.
