### ISSUE TITLE
Linux building (Error 2 / Error 1)

### ISSUE THREAD

**Issue by Yaksinikos** [TES3MP/TES3MP#117]
Linux Mint 18.1
build last version output;

> 
> ../../components/libcomponents.a(lightcontroller.cpp.o):(.data.rel.ro._ZTVN9SceneUtil15LightControllerE[_ZTVN9SceneUtil15LightControllerE]+0x210): Nicht definierter Verweis auf `virtual thunk to osg::NodeCallback::run(osg::Object*, osg::Object*)'
> collect2: error: ld returned 1 exit status
> apps/openmw/CMakeFiles/openmw.dir/build.make:6406: die Regel für Ziel „openmw“ failed
> make[2]: *** [openmw] Error 1
> CMakeFiles/Makefile2:349: die Regel für Ziel „apps/openmw/CMakeFiles/openmw.dir/all“ failed
> make[1]: *** [apps/openmw/CMakeFiles/openmw.dir/all] Error 2
> Makefile:127: rule for „all“ failed
> make: *** [all] Error 2
> All done! Press any key to exit.
> May Vehk bestow his blessing upon your Muatra.

All builds work, only tes3mp wont work.
Also I got the build once on the Dec. 24, but after trying it again it failed :/
The one which build succesfull works also for entering the local server, just the NPCs wont move :/

**Comment by davidcernat** [comment]
The NPCs aren't implemented yet. Hence, your build works fine.

**Comment by Yaksinikos** [comment]
> Hence, your build works fine.

Why does it sometimes build the tes3mp (executable) and sometimes not :confused: even if I use same source.

**Comment by davidcernat** [comment]
I don't know, because that doesn't make any sense. Maybe you've made a mistake somewhere.

**Comment by Yaksinikos** [comment]
Use this install script: [here](https://github.com/Translator5/Misc/commit/ed88d99fcfe86edf0834a8b643c0db52319a745c) with my own minor edits. Also used 0.4 release.
While using the script, I commented the source download line so that I m able to use my own code.

**Comment by Yaksinikos** [comment]
Got it 
Ref. [here](https://github.com/GrimKriegor/Misc/pull/5#event-906664804)
> LM18.1 libopenscenegraph is v.3.2.1
> replaced by libopenscenegraph-3.4-dev of openmw ppa

Thanks to "K1ll" of openmw-freenode chat
