### ISSUE TITLE
TES3MP logos and designs discussion

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#13]
Hello there gentlemen. It is way too early to think about such superficial things such as this, but it is also a good idea to set up a place where people can discuss and share ideas regarding this in the future.

Sooner or later we will be needing a logo to distinguish us from the OpenMW project.
Feel free to share your ideas and suggestions here.

**Comment by GrimKriegor** [comment]
Allow me to start by sharing a derpy icon/logo made from OpenMW's current Moon and Star. 

![tes3mp](https://cloud.githubusercontent.com/assets/1028205/16846886/1e337558-49e6-11e6-892c-964fe0182a74.png)

The multiple stacked logos suggest multiplayer, as you can obviously tell.

I was unable to ascertain which license are they using for this logo, so if you find out please lemme know.

**Comment by testman42** [comment]
Another derpy attempt:
![TES3MP_logo_suggestion](http://i.imgur.com/nk987TK.png)

In my eyes it does look different enough from original OpenMW logo, but still recognisable enough for users to get the intention.
I tried playing around with having multiple smaller starts in the place of big one, either overlaping or not, but most combinations turn out to be messy pile of pixels.

**Comment by GrimKriegor** [comment]
@testman42 Pretty cool, really like that one, thanks for your time.
Earlier the team was hinting to the possibility of making a contest of some sort, that might be fun. I'll keep you posted.

**Comment by ghost** [comment]
![tes3mp_logo](https://cloud.githubusercontent.com/assets/16569559/17233265/080e7976-54f4-11e6-9f75-d0954d4fc48b.png)

Here's a really quick attempt.  I've been trying to come up with a symbol to replace the star that instantly makes you think of "multiplayer."

**Comment by GrimKriegor** [comment]
I also like your idea @Texafornian and that color scheme is just perfect. Do you think it would look even better if the planet was Nirn, or at least we got to see Tamriel as the main continent?

**Comment by ghost** [comment]
That's a great idea, I'll try it out.

**Comment by ghost** [comment]
![tes3mp_logo_nirn](https://cloud.githubusercontent.com/assets/16569559/17257603/79b9584a-5588-11e6-9a8e-01f69523b61a.png)

**Comment by Koncord** [comment]
Much better. You can add noise (like on moon) on the Nirn?

**Comment by GrimKriegor** [comment]
@Texafornian love it, great job, I'll have to follow @Koncord on the noise suggestion, it would be great to give it some texture, a bit like the first logo you posted, that had the Earth with an atmosphere.
It would also be extra cool if Atmora was showing, since we can see the north pole.

Thanks for taking your time to provide suggestions, sera. :D

**Comment by ghost** [comment]
![tes3mp_logo_nirn_2b](https://cloud.githubusercontent.com/assets/16569559/17268128/c69770d6-55e5-11e6-9401-1083ab6d13ff.png)

Thanks for the feedback!  Wasn't Atmora destroyed?

**Comment by GrimKriegor** [comment]
@Texafornian Damn man, that looks amazing, love it, excellent job. Its great how Vvanderfell is right there, in our faces, the color scheme and the texture are just right.

Allow us to share this between the team, I am sure they will love it as well.

On a side note, since this is partially based on the OpenMW logo, it would be a good idea to check which license they released the logo under. Its prolly something libre tho. I'll try to find out.

Thanks for your time, are you usually on the Steam chat?

PS: I believe Atmora became uninhabitable over time, but the landmass is probably still there.

**Comment by davidcernat** [comment]
While I love the idea and think your effort looks beautiful, the map on the globe is too distorted and not lore-friendly at all.

For example, on your map Skyrim is basically non-existent, there's somehow a land bridge to Solstheim, eastern Morrowind is conspicuously wide, Topal Bay at the south end of Cyrodiil is really huge for some reason, Summerset Isle looks nothing like Summerset Isle, the coastline looks wrong all over, and so on.

If you can redo it so it looks more like maps of Tamriel, that will be greatly appreciated.

http://www.imperial-library.info/content/tamriel-maps

**Comment by ghost** [comment]
This version has all of the suggestions posted so far:

![tes3mp_logo](https://cloud.githubusercontent.com/assets/16569559/17443518/a057dfbc-5b00-11e6-8b9e-0c01a348fdf3.png)

I posted a message on dokterdume's deviantart page (he created the logo used by OpenMW) asking for permission to use this modification and I'm waiting for his response.

**Comment by davidcernat** [comment]
An excellent improvement and very accurate geographically now. If you can make it just a little bit darker and grainier – a bit more like the previous version as far as its shading goes – it will really be perfect.

**Comment by ghost** [comment]
Two more options:

![canvas](https://cloud.githubusercontent.com/assets/16569559/17447342/881abf60-5b13-11e6-80c8-80c33a3c92d4.png)

**Comment by davidcernat** [comment]
I like the one on the right more because the shading seems a bit nicer and Summerset Isle is visible in it.
