### ISSUE TITLE
Linux server binary releases

### ISSUE THREAD

**Issue by ijemafe** [TES3MP/TES3MP#132]
Can this project provide statically-linked / portable binary releases for the Linux server?

I tried compiling with the scripts [here](https://github.com/GrimKriegor/Misc/tree/ed88d99fcfe86edf0834a8b643c0db52319a745c/TES3MP-deploy), but compilation failed since `libswresample-dev` depends on `libavutil-dev=6.11.*` while Debian Jessie ships with `7.3.*`.

Edit: Some possible architectures to target are `i386`, `amd64`, `armv7l` (raspberry pi).

**Comment by Koncord** [comment]
You can try modify [this script](https://gist.github.com/Koncord/19f6339b1cee9484b82ba73b6a61f95d) for ARM. I cannot make binaries because I use latest GCC and libc on Linux Mint 18.1.

**Comment by davidcernat** [comment]
I don't see Linux server binary releases in my crystal globe.
