### ISSUE TITLE
Document all script functions

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#14]
_Originally posted by @Koncord_
[Functions](https://github.com/TES3MP/TES3MP/blob/master/apps/openmw-mp/Script/ScriptFunctions.hpp)

**Comment by davidcernat** [comment]
This has been finished for 0.6.x as of 311f770de715c7edc83b8f1490e48dd39feb09b6

Meanwhile, 0.7.x has its own documentation repo at https://github.com/TES3MP/TES3MP-Docs
