### ISSUE TITLE
Default NPC Dialogue Topics

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#179]
These lines are included in the vanilla CharGen process and give players basic dialogue topics to choose from when talking to NPCs:

AddTopic, "someone in particular"
AddTopic, "specific place"
AddTopic, "latest rumors"
AddTopic, "little advice"
AddTopic, "little secret"
AddTopic, "background"
AddTopic, "my trade"
AddTopic, "services"

I'm not sure which files control character creation in TES3MP so I'm just leaving this as an "issue" for future reference when it's to be implemented.

**Comment by davidcernat** [comment]
This hasn't really been an acknowledged issue given our lack of NPC functionality in general, but it should be fixed as soon as we have topic packets.

**Comment by davidcernat** [comment]
This is now easy to resolve in Lua scripts as of commit dbdb11b5f07a4a7c5d8ac155f87f86d69ff04e6f.
