### ISSUE TITLE
Readme for repo

### ISSUE THREAD

**Issue by Koncord** [TES3MP/TES3MP#19]

**Comment by GrimKriegor** [comment]
Here's a simple one, feedback appreciated :D
https://github.com/TES3MP/openmw-tes3mp/commit/fa30dad01cb3cecf9e52f84fb0807fe380bbe28d

---

# TES3MP

TES3MP is a project aiming to add multiplayer functionality to [OpenMW](https://github.com/OpenMW/openmw), a free and open source recreation of the popular Bethesda Softworks' game "The Elder Scrolls III: Morrowind".
- Version: 0.01
- License: GPLv3 (see docs/license/GPL3.txt for more information)
- Website: https://steamcommunity.com/groups/mwmulti

Font Licenses:
- DejaVuLGCSansMono.ttf: custom (see docs/license/DejaVu Font License.txt for more information)

## Project Status

[Version Changelog](https://github.com/TES3MP/openmw-tes3mp/blob/master/OpenMW-mp%20changelog)
We are still in a very early phase of development, at the moment we have synchronization of character appearance, character skills, stats, attributes and death as well as movement on interiors and exteriors, melee and ranged combat.

## Contributing

Development has been somewhat fast but we are severely understaffed, any contribution regarding [code](https://github.com/TES3MP/openmw-tes3mp/blob/master/CONTRIBUTING.md), documentation, bug hunting, artwork or nice Jobasha's gift cards are greatly appreciated.
Test sessions are often advertised in our Steam Group, there is also a chat room there.
Feel free to contact any of the [team members](https://github.com/TES3MP/openmw-tes3mp/blob/master/TES3MPTeam.md) for any questions you might have.

## Getting Started
- [Community forums](https://steamcommunity.com/groups/mwmulti)
- [Installation and build instructions](https://github.com/TES3MP/openmw-tes3mp/wiki/Installation-and-build-instructions)
- [Known issues and bug reports](https://github.com/TES3MP/openmw-tes3mp/issues)
