### ISSUE TITLE
Can't connect to the master server

### ISSUE THREAD

**Issue by lino1000** [TES3MP/TES3MP#221]
Today I found out about the multiplayer and wanted to give it a try. I got OpenMW to run normally and everything but when I start a server it connects to the master server and right after that it says "Lost connection to master server: 137.74..159.12:8080" I forwarded the port, tried starting it as admin and obviously got internet connection otherwise I couldnt send this. I opened the server browser and my server shows up there but with 999 ping and when I try to connect it just freezes and i have to close it again. I dont know if something is wrong with my laptop, the settings, the files or if the server is just shut down at the moment

Edit : since there are no other server online I cant tell if its me or the server either

**Comment by Koncord** [comment]
Fixed.

**Comment by lino1000** [comment]
nice it works now. that went much faster than i thought XD
