### ISSUE TITLE
Player-made potions cannot be shared

### ISSUE THREAD

**Issue by NullCascade** [TES3MP/TES3MP#233]
Version: 0.6-alpha-20170623A

When placing player-made potions into the world, other players cannot see or interact with them. Placing these potions in chests still won't let other players see them. Closing and re-opening the chest will result in the potion being lost.

**Comment by NullCascade** [comment]
Custom made potions also seem to vanish on server reboot or relog.

**Comment by testman42** [comment]
Custom items (potions, enchanted items, custom spells) are not implemented yet.
@davidcernat This seems to come up often. Would it make sense to make a list of implemented features or list of yes-we-know-this-doesn't-work features?

**Comment by testman42** [comment]
Actually wait, this is a duplicate of issue just below this one.

**Comment by davidcernat** [comment]
For a long time, at Koncord's behest, this feature was supposed to only get added to the rewrite started in 2d0840cb3ab5b0d4f0d34c60f5d44789379ed192. With that rewrite not working out and being put on hold, I've gone ahead and added the feature to the pre-rewrite instead, primarily as part of b57807407afa8b1cb50026422c20278f73d56632, TES3MP/CoreScripts@426187a171a54ac74e1ca3a139549d694d459e86 and TES3MP/CoreScripts@9cd5dc8556b26a0524b10676067a14830bf79a86, and I'll be merging that same implementation into the rewrite – with the extensive necessary adjustments – when I have more time.
