### ISSUE TITLE
Can't register in the game

### ISSUE THREAD

**Issue by 777Raim** [TES3MP/TES3MP#237]
Can't register in the game: after enter the nickname, there are not textbox to enter a password.
In terminal, there are interesting thing:
`[2017-07-10 11:45:07] [INFO]: ID_GUI_MESSAGEBOX, Type 3, MSG Create new password:
DataManager::getData: Failed to open 'tes3mp_text_input.layout'
Error in framelistener: MyGUI EXCEPTION : root widget name '_Main' in layout 'tes3mp_text_input.layout' not found.
 in MyGUI at /home/raim/Games/TES3MP-deploy/code/apps/openmw/mwgui/layout.cpp (line 32)
`
p.s. TES3MP was installed by TES3MP-deploy script

**Comment by davidcernat** [comment]
Should be fixed by c9c00d9. Please try rebuilding and using the updated resources folder.
