### ISSUE TITLE
Wild "endif" running amok 

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#24]
Noticed this yesterday on the client output, @davidcernat says it has been there for a while.
Doesn't seem high priority, but its a good idea to document it while its location is still unknown.

![endif](https://cloud.githubusercontent.com/assets/1028205/17191881/09dea484-5444-11e6-98fa-e16fe5813df1.jpg)

**Comment by davidcernat** [comment]
The following link suggests this is a problem with Morrowind's own game scripts:

http://forum.openmw.org/viewtopic.php?f=8&t=3677

Therefore, if this were to be fixed, it should be fixed in OpenMW itself.
