### ISSUE TITLE
Tutorial trap [BUG]

### ISSUE THREAD

**Issue by nalal** [TES3MP/TES3MP#241]
If you enter the tutorial area, you'll find yourself stuck as the door to get your papers is locked and you can't leave unless you get them from behind a lvl 100 locked door and it will ask you to take the ring from the barrel to your right when in the outdoor area but you can't leave if someone already took it.

This can be fixed by simply disabling the tutorial through a mod but seeing as there is no way to force clients to download mod files it tends to just drive players away

Examples:
![1](https://user-images.githubusercontent.com/6955074/28243276-3c677e3c-6981-11e7-817a-77eee4314bbb.png)
![2](https://user-images.githubusercontent.com/6955074/28243278-3c688264-6981-11e7-9be8-d89a816cf62c.png)
![3](https://user-images.githubusercontent.com/6955074/28243277-3c686202-6981-11e7-9086-cc9d4fb1b890.png)

**Comment by davidcernat** [comment]
Solved by TES3MP/PluginExamples@8cee25eadd5c09fbee559458655eedd6b261770f
