### ISSUE TITLE
Build fails on Arch Linux 

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#254]
I used the tes3mp-deploy script and all looks good, until the end:

[100%] Linking CXX executable ../../tes3mp-server
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(BitStream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakNetTypes.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakPeer.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakPeerInterface.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakString.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(ReliabilityLayer.cpp.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(StringCompressor.cpp.o): relocation R_X86_64_32 against symbol `englishCharacterFrequencies' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(DR_SHA1.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(GetTime.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(Itoa.cpp.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakSleep.cpp.o): relocation R_X86_64_32 against symbol `fakeMutex' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(Rand.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(SuperFastHash.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(CCRakNetSlidingWindow.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(DS_HuffmanEncodingTree.cpp.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(PluginInterface2.cpp.o): relocation R_X86_64_32S against symbol `_ZTVN6RakNet16PluginInterface2E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(RakNetSocket2.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(TCPInterface.cpp.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(DS_ByteQueue.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/raknet/build/lib/libRakNetLibStatic.a(SocketLayer.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/callff/build/src/libcallff.a(call.cpp.o): relocation R_X86_64_32 against symbol `__gxx_personality_v0@@CXXABI_1.3' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/elektroll/git/TES3MP-deploy/dependencies/callff/build/src/libcallff.a(callgen_SysV_x86_64.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [apps/openmw-mp/CMakeFiles/tes3mp-server.dir/build.make:1040: tes3mp-server] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: apps/openmw-mp/CMakeFiles/tes3mp-server.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

>> Creating symlinks of the config files in the build folder

>> Creating symlinks for resources inside the config folder

>> Creating useful shortcuts on the base directory

All done! Press any key to exit.
May Vehk bestow his blessing upon your Muatra.

**Comment by WizardCarter** [comment]
There's another issue a couple days older which states a similar problem on Ubuntu 16.04. It seems that TES3MP is intended to be built with GCC 7. Check your gcc version with gcc --version

**Comment by ghost** [comment]
My Version of GCC is 7.1.1 20170630

**Comment by ghost** [comment]
Problem fixed with this [commit](https://github.com/GrimKriegor/TES3MP-deploy/commit/b00084d2921142a4262c8e132e19cec5399e4e3a). It was a symlink problem in the deploy script.
