### ISSUE TITLE
Cannot Open Console

### ISSUE THREAD

**Issue by asg0451** [TES3MP/TES3MP#256]
I cannot open the console ingame. Got stuck in some rocks...
Tried rebinding key, had the same effect, which was to snap my camera to a certain position.
Windows 10, 64 bit.
My friend is having this issue as well with a similar setup.
Happy to provide any information necessary.

**Comment by ghost** [comment]
This is most likely working as intended.

The use of the console is restricted by the server, the server owner allows or disallows specific characters use of the console. By default, clients are not allowed to open the console.
If this is on your own server, you must set yourself as allowed to use the console in your character's data JSON file.

**Comment by asg0451** [comment]
you are absolutely right. I managed to find a Steam page which talks about this. My bad and thanks for the quick response.

**Comment by andresmrm** [comment]
For reference, setting myself to `rankStaff:2` didn't work. I had to to edit `config.lua` and set `config.allowConsole = true`.
Based on:
https://steamcommunity.com/groups/mwmulti/discussions/1/133258593388999187/

**Comment by davidcernat** [comment]
It's staffRank, not rankStaff.

**Comment by andresmrm** [comment]
Ops! I wrote it wrong here, but right in the config file (it was already written, I just changed the number). But, as I said, it didn't work for me...

**Comment by davidcernat** [comment]
Which version of TES3MP are you using?

**Comment by andresmrm** [comment]
```
TES3MP dedicated server 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Commit hash: 292536439e
```

**Comment by davidcernat** [comment]
Can you copy-paste the settings part of your player JSON file for me?

**Comment by andresmrm** [comment]
Sure!

```
  "settings":{
    "difficulty":"default",
    "enforcedLogLevel":"default",
    "physicsFramerate":"default",
    "consoleAllowed":"default",
    "bedRestAllowed":"default",
    "wildernessRestAllowed":"default",
    "waitAllowed":"default",
    "staffRank":2
  },
```
Reading these options again, now I saw the `consoleAllowed`. Setting it to `true` also works (even with `config.allowConsole = false` in config.lua).

**edit:** and even if `"staffRank":0`.

**Comment by davidcernat** [comment]
Well, admins don't have the console enabled by default either. You just give them a staffRank of 2 so they can use "/setconsole <pid> on" on themselves.

**Comment by andresmrm** [comment]
Thanks for the replies, but how to use "/setconsole on" without console?

**Comment by davidcernat** [comment]
"/setconsole on" is not a console command. It's a chat window command.

**Comment by andresmrm** [comment]
Hmmm, got it! Thanks!
