### ISSUE TITLE
Unable to connect to localhost server

### ISSUE THREAD

**Issue by abelsromero** [TES3MP/TES3MP#257]
I am unable to connect to a local server I just started.

I would expect to be able to connect to a local server without having to go through the master server but seems impossible.
To do so:
. I updated `destinationAddress` in `tes3mp-client-default.cfg` with `127.0.0.1`
. Aligned mods in my openMW configuration files
. Started `tes3mp.exe`

It initially connects because if I don't match the mods list or the IP is wrong (private IPS fail) it fails.
However, after loading the game and showing the login screen for a split seconds, it stops with the message `We have been disconnected`.

I understand I need to setup port-forwarding for others to connect, but I need to go though public internet to connect to my own server?

**Comment by davidcernat** [comment]
Does the server also get closed when you get disconnected?

**Comment by abelsromero** [comment]
I just did clean re-install and now it works :/

From dev-to-dev, you know how it feels right?

**Comment by Translator5** [comment]
Had same case here, but fixed by disabling firewall :laughing:
