### ISSUE TITLE
Players stop using their walking and running animations

### ISSUE THREAD

**Issue by davidcernat** [TES3MP/TES3MP#26]
Sometimes a player will stop using their walking and running animations on other clients, while still being displayed correctly whenever doing something else, such as jumping.

**Comment by Koncord** [comment]
Bug with wrong Strength value on others clients. These clients think that player (without anim) is overloaded

**Comment by davidcernat** [comment]
Fixed by 03d6e0cb62f12302e88616f3abbd39cf5c3dd870.

**Comment by davidcernat** [comment]
This still happens now, albeit more rarely. Needs to be fixed again.

**Comment by Koncord** [comment]
Never happened on 0.5.x-0.6. If this bug will happens again, we can simply reopen this issue.
