### ISSUE TITLE
Player enchanted items do not save

### ISSUE THREAD

**Issue by PhoenixTheSage** [TES3MP/TES3MP#260]
Per the title, items that the player enchants do not save to JSON data and will be removed from the players inventory upon logging out.

Edit: Seems to be a duplicate of https://github.com/TES3MP/openmw-tes3mp/issues/232 and https://github.com/TES3MP/openmw-tes3mp/issues/233

**Comment by WizardCarter** [comment]
Custom Enchantments have don't save yet.That's a feature that's still under development.

**Comment by PhoenixTheSage** [comment]
Well, yes obviously. This information is not posted anywhere though, and such this issue seemed necessary to log the missing feature.

**Comment by ghost** [comment]
Hi Phoenix, please see the 0.6.0 release announcement:
https://steamcommunity.com/groups/mwmulti#announcements/detail/1441567597386587897

**Comment by PhoenixTheSage** [comment]
Gotcha, thank you, but not everyone goes to steam for info. 
Bugs and feature tracking information needs to be on Github.

**Comment by davidcernat** [comment]
For a long time, at Koncord's behest, this feature was supposed to only get added to the rewrite started in 2d0840cb3ab5b0d4f0d34c60f5d44789379ed192. With that rewrite not working out and being put on hold, I've gone ahead and added the feature to the pre-rewrite instead, primarily as part of b57807407afa8b1cb50026422c20278f73d56632, TES3MP/CoreScripts@426187a171a54ac74e1ca3a139549d694d459e86 and TES3MP/CoreScripts@9cd5dc8556b26a0524b10676067a14830bf79a86, and I'll be merging that same implementation into the rewrite – with the extensive necessary adjustments – when I have more time.
