### ISSUE TITLE
Enable destroying items

### ISSUE THREAD

**Issue by abelsromero** [TES3MP/TES3MP#262]
*feature request*

*Currently..*
When using the `disable` command to make an item disappear, the item reference remains in the JSON cell files with `"state":false`.

*As a server administrator...*
I'd like to be able to list and destroy disabled items to prevent server degradation.

**Comment by ghost** [comment]
You can just use "setdelete 1" after targeting the object.

However, it's recommend to use "disable", then wait a second, then use "setdelete 1" when trying to delete objects that have local scripts.

**Comment by davidcernat** [comment]
"setdelete 1" is the correct option. Disabling is more for temporarily hiding items.

**Comment by abelsromero** [comment]
Nice!
But, still there's no easy way to list the disabled objects once you close the commands window or leave a game. Or I am wrong?

Btw, this is a low priority feature request to improve server maintenance in the long run.

**Comment by davidcernat** [comment]
You can iterate through the state packets in your cell data to find the objects that are disabled.

**Comment by ghost** [comment]
> However, it's recommend to use "disable", then wait a second, then use "setdelete 1" when trying to delete objects that have local scripts.

Shouldn't be necessary with OpenMW, you can directly use setdelete.

**Comment by davidcernat** [comment]
This is more an issue for the Lua scripts repo (if at all), so I'm closing it here.
