### ISSUE TITLE
Assertion failure when adding bk_irano_note via the in-game console

### ISSUE THREAD

**Issue by grebenyukaa** [TES3MP/TES3MP#274]
Steps to reproduce:
1. Open in-game console and add bk_irano_note:
  `player->AddItem bk_irano_note 1`

1. Client crashes, reporting:
>[2017-08-24 21:02:36] [INFO]: Sending ID_OBJECT_PLACE about Mournhold, Royal Palace: Courtyard
> \- cellRef: bk_commontongue_irano, count: 1
>[2017-08-24 21:02:36] [INFO]: Received ID_OBJECT_PLACE about Mournhold, Royal Palace: Courtyard
> \- cellRef: bk_commontongue_irano, 0, 6537, charge: -1, count: 1
>tes3mp: /tmp/nix-build-tes3mp-0.6.0.drv-0/TES3MP-deploy-ac2e862c3b96206d8e0678d422ece30f9f2d0f45-src/code/apps/openmw/mwmp/../mwworld/ptr.hpp:69: MWWorld::CellStore* MWWorld::Ptr::getCell() const: Assertion \`mCell' failed.
>/home/amadeus/nixpkgs/result/bin/tes3mp: line 4:  2561 Aborted                 (core dumped) ./tes3mp

When adding this note normally (a.k.a. picking up from the floor), this issue cannot be experienced. Also, if there is more than one such note in your inventory, the client will always crash on logon with the same assertion failure.

This note is a quest one, needed for "Disloyalty Among the Guards" (TR07_Guard) quest. While script sync is still a not implemented feature, this note may not appear during normal gameplay, at least, that's what happened to me.

**Comment by davidcernat** [comment]
Already fixed by d51736d68fd46d6b0f197aaf7e1a84883f41a265 14 days ago.
