### ISSUE TITLE
Affecting other players effects are not synchronized sometimes

### ISSUE THREAD

**Issue by grebenyukaa** [TES3MP/TES3MP#275]
Sometimes the following situation occurs:
Alice and Bob are playing together. Alice succesfully hits Bob with the paralyzing dagger seeing the paralysis animation (a green cloud for that matter). However, Bob has no active paralysis effect on his client and can move around freely. From Alice's point of view (on her client), Bob's animation is frozen, but his position is constantly updated - so he is "moving" around with disabled animation. When the paralysis timer expires, Bob's animation becomes enabled again.

This issue is sporadically reproducible and seems to affect not only the paralysis effect. Also, this issue seems not to affect effects applied to NPCs by other players.

**Comment by davidcernat** [comment]
As mentioned in the release announcement for 0.6.0:

> Spells cast through items are not yet synchronized.

I'll try to fix it soon though.

**Comment by testman42** [comment]
Isn't this fixed in 0.6.1 now?
Time to close the issue IMHO.

**Comment by davidcernat** [comment]
No. It's not.
