### ISSUE TITLE
Build fails on Debian sid

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#278]
Building under Debian sid using the automated install script gives me the following:
`CMakeFiles/tes3mp.dir/mwgui/textinput.cpp.o: In function 'MWGui::TextInputDialog::getTextInput[abi:cxx11]() const':
textinput.cpp:(.text+0x27b): undefined reference to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
CMakeFiles/tes3mp.dir/mwgui/console.cpp.o: In function 'MWGui::Console::keyPress(MyGUI::Widget*, MyGUI::KeyCode, unsigned int)':
console.cpp:(.text+0x5673): undefined reference to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
console.cpp:(.text+0x569a): undefined reference to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
console.cpp:(.text+0x5893): undefined reference to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
CMakeFiles/tes3mp.dir/mwgui/console.cpp.o: In function 'MWGui::Console::acceptCommand(MyGUI::EditBox*)':
console.cpp:(.text+0x6fb1): undefined reference to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
CMakeFiles/tes3mp.dir/mwgui/messagebox.cpp.o:messagebox.cpp:(.text+0x865): more undefined references to 'MyGUI::UString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const' follow
collect2: error: ld returned 1 exit status
apps/openmw/CMakeFiles/tes3mp.dir/build.make:7110: recipe for target 'tes3mp' failed
make[2]: *** [tes3mp] Error 1
CMakeFiles/Makefile2:501: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/all' failed
make[1]: *** [apps/openmw/CMakeFiles/tes3mp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by crsleeth** [comment]
Hello. I'm getting a similar error on Ubuntu 16.04.3 64-bit:
`/home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp: In member function ‘void mwmp::DedicatedActor::equipItem(std::__cxx11::string, int)’:
/home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:28: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                            ^
/home/ryan/TESMP-deploy/code/apps/openmw/mwmp/DedicatedActor.cpp:239:61: error: use of ‘ptr’ before deduction of ‘auto’
     for (const auto &ptr : ptr.getClass().getInventoryStore(ptr))
                                                             ^
apps/openmw/CMakeFiles/tes3mp.dir/build.make:6038: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o' failed
make[2]: *** [apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:501: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/all' failed
make[1]: *** [apps/openmw/CMakeFiles/tes3mp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

My Debian Stretch 9 64-bit install kernel panics (I'll make a separate issue for this) at: 
![debian](https://user-images.githubusercontent.com/13802587/30005447-c9bdb034-90b0-11e7-818d-fe6c9d87412e.PNG)

Going to try Fedora next, hopefully that works I'd really hate to have to host on Windows.

**Comment by davidcernat** [comment]
This seems like it was caused by using the wrong version of MyGUI. I'm going to go ahead and assume it's no longer happening with current versions, because no one has reported it in a long time.
