### ISSUE TITLE
No Default Settings Found

### ISSUE THREAD

**Issue by Nakotobana** [TES3MP/TES3MP#279]
So, I've got a server successfully running and one of my two friends are able to join and play fine. The other friend however, keeps getting the error message, "No default settings found! Make sure 'tes3mp-client-default.cf' was properly installed" whenever they try to run tes3mp.exe. They've deleted and re-extracted the Tes3MP stuff a couple times now, but continue to get the same error

**Comment by davidcernat** [comment]
Sounds like some kind of file permission problem. Does it help if your friend runs TES3MP as an administrator?

**Comment by Nakotobana** [comment]
I had them reinstall OpenMW entirely and I guess that workes for whatever reason, but ill try that solution next time it occurs
