### ISSUE TITLE
TES3MP-Browser occasionally hangs the entire system

### ISSUE THREAD

**Issue by LunarArcanus** [TES3MP/TES3MP#330]
This is an issue that I had in 0.6.0 as well. Sometimes, when I start the server browser, it freezes up everything. In some cases, I can open up Task Manager (slowly) and kill the process, and other times I have to do a hard reboot with the power button as I just can't get the control back.

It feels like a memory leak of some sort within the application and seems to take up all the available memory and CPU.

I'm on Windows 8, using TES3MP 0.6.1 (like I said, it was in the previous version as well).

**Comment by Koncord** [comment]
Possibly fixed by:
https://github.com/TES3MP/RakNet/commit/6226bbbf30ffdc4acb5315a77bbb4f880f3a080e
https://github.com/TES3MP/openmw-tes3mp/commit/35b771b19e00a813350553f686c0971334bbc3b5
https://github.com/TES3MP/openmw-tes3mp/commit/5b8f4f3e92d662f36580b94184057b648be9f01d
