### ISSUE TITLE
Camera turning problem; camera stops rotating to the left for no apparent reason

### ISSUE THREAD

**Issue by stonelike** [TES3MP/TES3MP#357]
I'm not sure why, but while I can move my mouse sideways to the right to cause my character/camera to rotate rightward as much as I want, I cannot correspondingly move my mouse to the left to do the same.  Leftward camera rotation abruptly stops after a short, finite arc (roughly 90*), for no apparent reason.

I can seemingly reset this constraint by rotating the camera slightly to the right, after which it turns left again until once again hitting an arbitrary stopping point.

I am pretty sure the problem isn't to do with my own controls or game settings, so I conclude it must be some kind of bug in how the mouse/camera controls are handled.

I am running 64-bit Linux (specifically a recent version of Ubuntu), using a USB mouse which shows no apparent signs of any hardware problems, and am running TES3MP 6.1 with only vanilla mods.

Thank you.

**Comment by testman42** [comment]
Hmm, did you maybe try if the same thing happens in OpenMW (preferabbly 0.42.0)?
Did you experience this issue with any other game?

**Comment by stonelike** [comment]
Hey, I restarted the game and it seems to have fixed itself.  I am not sure what caused the issue in the first place.

If it helps, I was running it in windowed mode, had alt-tabbed between some other windows during play, and I had changed the video resolution a couple times while in-game.  I'm not sure what else might have affected it.

**Comment by testman42** [comment]
Hm, strange. I encountered similar issue one time when I was running a game with WINE fullscreen but the rotation stopped as if / when the mouse has hit the border of the screen. So if you were in windowed mode, this could not have been the case.

Still, happy to see it solved itself. 👍
