### ISSUE TITLE
Build fails on Msys2

### ISSUE THREAD

**Issue by CyberSys** [TES3MP/TES3MP#358]
Scanning dependencies of target tes3mp-server
Scanning dependencies of target tes3mp
[ 26%] Building CXX object apps/openmw-mp/CMakeFiles/tes3mp-server.dir/main.cpp.obj
In file included from E:/Dev/tes3mp_msys2/code/apps/openmw-mp/Player.hpp:22:0,
                 from E:/Dev/tes3mp_msys2/code/apps/openmw-mp/main.cpp:21:
E:/Dev/tes3mp_msys2/code/apps/openmw-mp/Script/LuaState.hpp:7:10: fatal error: sol.hpp: No such file or directory
 #include "sol.hpp"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [apps/openmw-mp/CMakeFiles/tes3mp-server.dir/build.make:63: apps/openmw-mp/CMakeFiles/tes3mp-server.dir/main.cpp.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:499: apps/openmw-mp/CMakeFiles/tes3mp-server.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…

**Comment by mupfdev** [comment]
You're trying to build the master branch (0.7.0-alpha). On purpose?
If so, you have to fetch the repositories submodule "sol" first.
Otherwise: switch to branch "0.6.1".

Best regards, mupf

**Comment by CyberSys** [comment]
Yes, thanks, I already fixed it
