### ISSUE TITLE
Can't write in chat

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#36]
Hello! I followed the instructions: install openmw, build client (on linux), connect to server play.suran.pl (it works!) but I can't type nothing in chat, keys don't react. I trying to press any keys, change layout, nothing helps. So I can't register on this server (but can enter name).

**Comment by davidcernat** [comment]
That server uses a Windows build of tes3mp from 10 days ago.

There is really no reason why you should expect a client built on Linux from the latest code to work with a server built 10 days ago.

Why don't you try hosting your own server and then connecting to yourself? That's how you find out if there's actually a problem with the code.

**Comment by ghost** [comment]
I don't actually know how to run my own server. I tried to launch openmw-mp, but it fails with error "Script not found: ~/ClionProjects/PS-dev/scripts/tes3mp.lua" (wrong path?).

**Comment by davidcernat** [comment]
How far have you gotten in this guide?

http://steamcommunity.com/groups/mwmulti/discussions/1/352788917749398364/

**Comment by ghost** [comment]
Never seen it. Thank you! I'll try.

**Comment by davidcernat** [comment]
I'm going to assume you've solved the problem. If not, feel free to let me know.

**Comment by ghost** [comment]
Ok, sure! When I find some friends for test my server, I necessarily tell about it here :D But actually I'm not sure. Maybe you can start some public server?

**Comment by ghost** [comment]
and tell about it in steam community, for example

**Comment by ghost** [comment]
I'm sorry if my English is bad. Do you have problems with a hosting?

**Comment by ghost** [comment]
I have a friends, that hosted "don't starve together" servers just for fun. Maybe I can attract them to host your server?

**Comment by davidcernat** [comment]
I don't see any point in hosting a public server based on the latest code every time it changes, seeing as how only people who have built the client on Linux would be able to join it.

I also see no point in doing constant Windows releases with the code changing as often as it does. I'd rather do them when we have a new feature to showcase.

So, if you really want to play with others, go ahead and revert your local copy of our repo to the last commit (8686b9cc12f1992e5630636cc113dd47093eadbc) used in the current Windows release, and then join the Suran server.

**Comment by ghost** [comment]
No! I talking about testing, not playing.

**Comment by davidcernat** [comment]
I start my own test server and give people the required build to join it whenever necessary. I see no need for it to be public and always on.

**Comment by ghost** [comment]
I can not be sure when the game will in production. I'm curious to test it :) it's very interesting and maybe we'll find some bugs.

**Comment by davidcernat** [comment]
Considering the major changes to networking that are coming, there is really not much you can report at the moment as a tester that will still be useful one week from now.

**Comment by ghost** [comment]
of course this a not public release, but we really can't test it on different platforms? as I know, raknet is crossplatform engine. where is a problem?

**Comment by davidcernat** [comment]
Did you miss the last paragraph in comment 240098311?

> So, if you really want to play with others, go ahead and revert your local copy of our repo to the last commit (8686b9c) used in the current Windows release, and then join the Suran server.

**Comment by ghost** [comment]
sorry :(

**Comment by ghost** [comment]
I wish you luck anyway. your work is awesome! :)

**Comment by Pollito001** [comment]
I test with my own server on Linux and I cant write in the chat and f2 key not work, any help?

**Comment by Pollito001** [comment]
I compile on Linux using install.sh , I using my own server and still not working, cant write or login,

**Comment by Koncord** [comment]
Maybe problem with script?  In manually building all fine. You have errors or warnings? You should attach server.log and openmw.log form ~/.config/openmw

**Comment by Pollito001** [comment]
NO warnings or problems during compilation

[openmw.log.txt](https://github.com/TES3MP/openmw-tes3mp/files/465238/openmw.log.txt)
[server.log.txt](https://github.com/TES3MP/openmw-tes3mp/files/465237/server.log.txt)

**Comment by Pollito001** [comment]
I forgot to mention im using Manjaro Linux

**Comment by Koncord** [comment]
You cannot open chat or not have focus in CommandLine? You can see your text in CommandLine when you typing?

**Comment by Pollito001** [comment]
No i cant open chat and no, no text in command.

**Comment by Koncord** [comment]
Can you check your tes3mp-client-default.cfg?

**Comment by Koncord** [comment]
I think Grim's shell script is slightly outdated. You should press Y for open chat.

**Comment by Pollito001** [comment]
Thats my tes3mp-client-default.cfg?:

``` ini
[General]
# 0 - Verbose (spam), 1 - Info, 2 - Warnings, 3 - Errors, 4 - Only fatal errors
loglevel = 0
server = 127.0.0.1
port = 25565
#name = Player

[Master]
address = master.tes3mp.com:8080

[Chat]
# Use https://wiki.libsdl.org/SDL_Keycode for rebinding keys
keySay = Y # For chatting
keyChatMode = F2 # For enabling or disabling the chat window
x = 0
y = 0
w = 390
h = 250
delay = 5.0 # How long the message will be displayed in hidden mode
```

**Comment by Koncord** [comment]
Yes, you sholud use:
Y # For chatting
F2 # For enabling or disabling the chat window

**Comment by Koncord** [comment]
By the way. You can create local config ~/.config/openmw/tes3mp-client.cfg
