### ISSUE TITLE
Selecting or using any power or spell will crash to desktop

### ISSUE THREAD

**Issue by domsson** [TES3MP/TES3MP#362]
**Setup:** Fresh install of 0.6.2 on Win 10, data from GOG's Morrowind GOTY edition.

If any player left-clicks on any spell or power from the inventory (right-click) screen, the game will immediately crash to desktop. The same happens if you use <kbd>F1</kbd> and place any power or spell on one of the hotkeys, then try to use said hotkey. Again, crash to desktop.

Happens on my own, local server, as well as on a public server (ashfall).  
Neither the client nor the server log contain any info that would indicate the crash.  
Not sure if OpenMW or TES3MP bug, so hopefully I'm reporting this in the right place.

**Comment by davidcernat** [comment]
Please refer to this:

https://www.reddit.com/r/tes3mp/comments/7mbrah/game_crashes_on_my_server_every_time_i_try_to/drsvp5t/

**Comment by domsson** [comment]
Thank you so much for your swift reply! I re-downloaded 0.6.2 and unpacked the contents over my existing TES3MP. Sadly, I'm still experiencing the crash described above.

**Comment by davidcernat** [comment]
Can you show me a screenshot of your tes3mp folder?

**Comment by domsson** [comment]
Of course. Will [this](https://imgur.com/a/uWrbY) do?

**Comment by domsson** [comment]
Hold on a second. I was actually dumb enough to unzip the earlier 0.6.2, not the one I just re-downloaded. The fix **does** seem to work. Thank you for your time and sorry for the confusion.

**Comment by davidcernat** [comment]
No problem.
