### ISSUE TITLE
0.6.2 hotfix not connecting to servers of the same version (0.6.2 hotfixed)

### ISSUE THREAD

**Issue by arcsteryx** [TES3MP/TES3MP#371]
i repeatedly redownloaded the latest version of tes3mp with the latest version on 1/17, each time i request to join a server it continues showing me a popup that says "Version mismatch! Your client is on version 0.6.2-hotfixed. Please make sure the server is on the same version."

**Comment by davidcernat** [comment]
This is completely intentional. The servers need to update to 0.6.2-hotfixed too.
