### ISSUE TITLE
Segmentation error disconnects after few seconds after join

### ISSUE THREAD

**Issue by UltraMCPL** [TES3MP/TES3MP#379]
When I try to move (leave cell) game disconnects and server halts. Why?

I have tried debian, ubuntu, archlinux. Client/server versions match (0.6.2-hotfix).

Am I missing something?

Do I have to have *.esm files on server? I dont.

Does my game language have to match server? I've tried matched and unmatched.

Is it permissions? Ran it as root and user.

Is it wizard settings? I've tried using Morrowind and Bloodmoon esm files.

Attaching last server log messages for refference https://pastebin.com/raw/G5RBVY71

**Comment by davidcernat** [comment]
The Linux release was broken for a couple of days. Try downloading it again because it should be fixed now:

https://github.com/TES3MP/openmw-tes3mp/releases/download/tes3mp-0.6.2/tes3mp-GNU.Linux-x86_64-release-0.6.2-hotfixed.tar.gz

**Comment by UltraMCPL** [comment]
I confirm it's working, thnx
