### ISSUE TITLE
Keep old logs for client and server

### ISSUE THREAD

**Issue by davidcernat** [TES3MP/TES3MP#38]
We should have a "logs" folder for automatically generated text logs.

Every time you start openmw.exe you should get a new client log, and every time you start openmw-mp.exe you should get a new server log, without overwriting previously existing logs.

This will be really useful for determining which series of packets have caused a desync or another problem, by cross-referencing logs from the server and various players.

**Comment by davidcernat** [comment]
Right now, opening the client or server overwrites your previous log for it.

It would be nice to keep previous logs as separate files.

**Comment by Koncord** [comment]
Solved by f7b4aea85b22256a9c09cddfe98431f24deb79bd
