### ISSUE TITLE
Edit players stats from server

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#4]
_Originally posted by @Koncord_

| **Function** | **Status** | **Description** |
| --- | --- | --- |
| [Get/Set]Name | :heavy_check_mark: |  |
| [Get/Set]BirthSign | :heavy_check_mark: |  |
| [Get/Set]CharClass | :heavy_check_mark: |  |
| [Get/Set][Health/Magic/Fatigue] | :heavy_check_mark: |  |
| [Get/Set]Current[Health/Magic/Fatigue] | :heavy_check_mark: |  |
| [Get/Set]Attributes | :heavy_check_mark: |  |
| [Get/Set]CurrentAttributes | :heavy_check_mark: |  |
| [Get/Set]Skills | :heavy_check_mark: |  |
| [Get/Set]CurrenSkills | :heavy_check_mark: |  |
| [Get/Set]IncreaseSkills | :heavy_check_mark: |  |
| [Get/Set]MajorSkills | :heavy_check_mark: |  |
| [Get/Set]Race | :heavy_check_mark: |  |
| [Get/Set]Head | :heavy_check_mark: |  |
| [Get/Set]Hairstyle | :heavy_check_mark: |  |
| [Get/Set]Class | :heavy_check_mark: |  |
| [Get/Set]IsMale | :heavy_check_mark: |  |

**Comment by davidcernat** [comment]
All the script functions mentioned here are confirmed to be implemented and functional as of 6650b7449809a448e593dba8c62f7252c0ee1794.
