### ISSUE TITLE
[Question] Installing Tes3Mp server on raspberry pi 3

### ISSUE THREAD

**Issue by Burgersim** [TES3MP/TES3MP#435]
I wanted to ask if this is even possible, since I tried the official release, but it seems that is made for AMD/Intel architecture, not ARM, or is there a possibility to get this running on ARM CPUs?

Sry if thhis may not be the right place for this question, I just thought the quickest way would be to ask here ^^*

Thanks in advance for your help

**Comment by robsob91** [comment]
If you can successfully pull in the dependencies and compile it, I see no reason why not. However the RPI would likely have performance issues.

**Comment by Burgersim** [comment]
Hmm ok maybe i did sthg wrong when pulling the dependencies, because compiling it didn't really work, but the already compiled zip is for x86 architectures, right?

So what specs would be recommended for running the server on a machine?

**Comment by AokiAhishatsu** [comment]
If you belive [this](https://www.reddit.com/r/tes3mp/comments/8jfr9b/server_on_a_raspberry_pi/), Raspberry Pi 2/3 and anything faster should work.
I haven't tried (yet).

**Comment by GrimKriegor** [comment]
ARMHF packages are now included in the [official release](https://github.com/TES3MP/openmw-tes3mp/releases).
