### ISSUE TITLE
balls

### ISSUE THREAD

**Issue by ascorii** [TES3MP/TES3MP#461]
my nuts? my fat fucking nuts?

**Comment by robsob91** [comment]
Check for testicular cancer. It happens.

**Comment by ascorii** [comment]
Thank you, Robsob91. You are the Bophades of this generation.

**Comment by ascorii** [comment]
![smiles](https://user-images.githubusercontent.com/40411398/43149787-56949de0-8f36-11e8-9c45-965602ac4dd9.jpg)
