### ISSUE TITLE
Friend see me stuck in place

### ISSUE THREAD

**Issue by Rastahan** [TES3MP/TES3MP#465]
Hi,
me and my friend have managed to create server only for us. We've logged in but after a few seconds, my friend saw my character stuck in place but I moved and saw her and mine character normally. I was walking around her but was invisible to her. I hope you understood. It's hard to explain.

**Comment by davidcernat** [comment]
What happens when a third person joins?

**Comment by davidcernat** [comment]
This sounds like it was caused by connection problems. Since we haven't heard back about it, I'm going to close this issue.
