### ISSUE TITLE
Playthrough issues

### ISSUE THREAD

**Issue by SallyMercury** [TES3MP/TES3MP#466]
Hi David,

First of all, TES3MP works awesome, thanks a lot David. I play with my boyfirend together as a fighter and a thief. We have already reached Bloodmoon. So far everything works quite smooth with several mods e.g. Morrowind Rebirth etc.. By the way is the Unofficial Morrowind Official Plugins Patched UMOPP necessary and compatible to tes3mp?. 
Because it is often necessary in the game to come back to the quest giver after certain days have passed, the question is how to skip days in the tes3mp client or server. Also if we logout and then in again, it counts again from day one which is quite annoying.
A lot of Tribunal quests did not trigger in Tribunal, as all NPCs refuse to talk due to City is under attack alarm, although we already finished the quest Attack on Mournhold. We often had to use console to get the remaining journal entries and to make the NPC enemies appear, which was immersion braking.
In the quest Corpus Cure we went to Tel Fyr, but unfortunately he gave only one of us the cure, hence we could not kill together Dagoth Gares. 
Finally I like to know if this is a bug or normal if I go to a mage guild to buy healing or magicka potion, I can do this endlessly, although the seller should only have three in stock at a time.
Looking forward for your new version with map, custom potions, custom spell and custom enchantment synchronization fully implemented. By the way are you still working on the new version? I haven't seen any new commits since last month. Keep up the great work, David.

Sally

**Comment by davidcernat** [comment]
Thanks for the kind words.

There are plenty of recent commits on the 0.7 branch, as you can see here: https://github.com/TES3MP/openmw-tes3mp/commits/0.7.0

As for quest issues, I've never been interested in fixing individual complicated scripted quests, and have instead taken a big picture approach where I've aimed to come up with a system that can fix all complicated scripted quests ever created for Morrowind by both its developers and its fans. It just hasn't made it in yet.

Of course, the FAQ is pretty clear about having to use the console now and then to progress in quests on this unfinished project, so complaints about immersion breaking are missing the point.

I can't really replicate your ability to buy potions endlessly unless I quit and rejoin the server, in which case it's related to merchant inventories not being synchronized.
