### ISSUE TITLE
Build fails on Debian 9

### ISSUE THREAD

**Issue by Retrnon** [TES3MP/TES3MP#472]
After running build, output is this:
> [ 74%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/LocalActor.cpp.o
[ 74%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/DedicatedActor.cpp.o
[ 74%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/ActorList.cpp.o
[ 74%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/ObjectList.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Worldstate.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Cell.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/CellController.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUIController.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/MechanicsHelper.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/RecordHelper.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/ScriptController.cpp.o
[ 75%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUI/GUIChat.cpp.o
/home/retrnon/Documents/TES3MP-deploy/code/apps/openmw/mwmp/RecordHelper.cpp: In function ‘void RecordHelper::overrideEnchantmentRecord(const mwmp::EnchantmentRecord&)’:
/home/retrnon/Documents/TES3MP-deploy/code/apps/openmw/mwmp/RecordHelper.cpp:290:10: warning: unused variable ‘isExistingId’ [-Wunused-variable]
     bool isExistingId = doesEnchantmentRecordExist(recordData.mId);
          ^~~~~~~~~~~~
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUI/GUILogin.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUI/PlayerMarkerCollection.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUI/GUIDialogList.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/GUI/TextInputDialog.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/BaseClientPacketProcessor.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/PlayerProcessor.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/ObjectProcessor.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/ActorProcessor.cpp.o
[ 76%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/WorldstateProcessor.cpp.o
[ 77%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/processors/ProcessorInitializer.cpp.o
[ 77%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/main.cpp.o
[ 77%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/engine.cpp.o
[ 77%] Linking CXX executable ../../tes3mp
[ 77%] Built target tes3mp
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by terabyte25** [comment]
Are you building the master branch? The master branch is broken right now. Try compiling 0.7.0 or 0.6.2 under branches.

**Comment by Retrnon** [comment]
I was building under 0.7.0 when the error occurred.

**Comment by terabyte25** [comment]
Try using Grim Kriegor's deploy script.

**Comment by terabyte25** [comment]
https://github.com/GrimKriegor/TES3MP-deploy

**Comment by davidcernat** [comment]
Any follow-up on this?
