### ISSUE TITLE
Level Progress Not Saving (0.7)

### ISSUE THREAD

**Issue by Dezmolish** [TES3MP/TES3MP#477]
First off, sorry if this is in the wrong place. If so please remove it and thank you for your time.

I downloaded the 0.7 Alpha update and the new features are awesome, y'all are doing grand! However, I have noticed that when I reload my characters, their level progress is reset to 0. I have tried new characters and a new world, but those don't seem to be the issue. I'm not sure if this is new to the alpha release, I've messed something up in settings (which I didn't mess with too much, so I doubt this is it), or if it has been here in the old updates, but I could not find a previous report on it. 

Again, sorry if this is in the wrong place and many thanks!

**Comment by davidcernat** [comment]
That has been hotfixed in the Lua scripts for all the available builds. Can you try downloading the build again or, alternatively, manually applying the changes in CoreScripts@4928774737fadb45e4247394355aba3c48f40191 ?

**Comment by davidcernat** [comment]
That has been hotfixed in the Lua scripts for all the available builds. Can you try downloading the build again or, alternatively, manually applying the changes in TES3MP/CoreScripts@4928774737fadb45e4247394355aba3c48f40191?

**Comment by Dezmolish** [comment]
I did not try downloading again, but I did do the manually. Worked like a charm! I'm sure it was just my computer being screwy. Thank you for the help and sorry for the false alarm!

**Comment by Dezmolish** [comment]
P.S. If you would like me to try it the other way, I’d be more then happy to but I think this thread is closed. (This may be dumb but I can’t seem to find where to close it)

**Comment by Dezmolish** [comment]
Found it!
