### ISSUE TITLE
LAN Connection returns with an error

### ISSUE THREAD

**Issue by witchcod3** [TES3MP/TES3MP#478]
you can not use a lan connection, it will load to the morrowind loading screen but when it tries to load areas it disconnects,

Loading config file: C:\Users\user\Documents\My Games\OpenMW/openmw.cfg... done.
Loading config file: ./openmw.cfg... done.
TES3MP client 0.7.0-alpha (Windows 64-bit)
Protocol version: 7
Commit hash: 292536439e
------------------------------------------------------------

**Comment by davidcernat** [comment]
This is confirmed to be untrue. We have plenty of people playing it on LAN.

Maybe you want to report a problem with loading in areas instead, which has nothing to do with LAN.

**Comment by terabyte25** [comment]
Can you test this with a public server please?

**Comment by terabyte25** [comment]
Also try using the latest build.
