### ISSUE TITLE
Trying to deposit items into a container beyond weight limit deletes item

### ISSUE THREAD

**Issue by Zwahili** [TES3MP/TES3MP#481]
1. A crate/chest etc has a max limit of 200 weight (for example)
2. A player tries to deposit something that would over-fill the crate
3. The UI throws "The item will not fit."
4. The item disappears

In OpenMW 0.44.0 (and supposedly OG MW) this causes the item to remain on the cursor.

The images show the overloading event both from the players perspective (the cursor was not included in the screencap apparently) and the server log (set to the second most verbose setting)
![screenshot004](https://user-images.githubusercontent.com/44374702/47305042-90bad780-d628-11e8-823b-48d18679eeb4.png)
![server](https://user-images.githubusercontent.com/44374702/47305043-91536e00-d628-11e8-97d4-ab7aedef287b.png)

In the server.png image; the wood cup and metal goblet (last two entries) were the ones that disappeared.

**Comment by Zwahili** [comment]
I can see now that tes3mp.com says "OpenMW version: 0.43.0". 
Did it not use to say 0.44.0?

**Comment by Zwahili** [comment]
Misclick...

**Comment by HalfThere** [comment]
Additionally, this causes new items to spawn: I was doing this with alchemy ingredients and it deleted the ones I tried to put it and increased the number of another ingredient I had

**Comment by davidcernat** [comment]
I expect this to be fixed as of afd17e5a48ae16ff83108e5ca9030d5adaa2ffba
