### ISSUE TITLE
Item duplication on joining a game

### ISSUE THREAD

**Issue by Olaxan** [TES3MP/TES3MP#482]
Every time me or my friend joins my server, a handful of items seem to return to our inventories. These are either items that we have discarded on the ground, sold, or put into containers on previous sessions. We first noticed this when my friend began getting duplicate Demon Katanas upon joining. Now we're both affected and it affects several items, like Glass Armor and named items like Maryon's Staff.

We have a few mods installed, but none related to inventory or items, as far as I know.

I believe we are running the latest version.

Logs:
[tes3mp-server-2018-10-23-21_26_23.log](https://github.com/TES3MP/openmw-tes3mp/files/2519336/tes3mp-server-2018-10-23-21_26_23.log)
[tes3mp-client-2018-10-23-21_26_36.log](https://github.com/TES3MP/openmw-tes3mp/files/2519337/tes3mp-client-2018-10-23-21_26_36.log)

**Comment by StevenC21** [comment]
I cannot fix your issue, but I would like to point out to the developers that the Demon Katana item is mentioned numerous times in the server log, even ignoring instances where it appears to have been used. I can't find anything of interest in the client log, however.

**Comment by Olaxan** [comment]
Here are the player files. A lot of references to Demon Katanas.

[Player JSON.zip](https://github.com/TES3MP/openmw-tes3mp/files/2520605/Player.JSON.zip)

**Comment by Olaxan** [comment]
Here are the player files. A lot of references to Demon Katanas.
Edited to remove IP addresses.

[Players.zip](https://github.com/TES3MP/openmw-tes3mp/files/2520615/Players.zip)

**Comment by HalfThere** [comment]
Having the same issue. It also deletes items; I can't seem to keep repair hammers or probes. It started with silver sabres for me - no Demon Katanas

**Comment by Javimel** [comment]
Happening for myself and a friend as well. My guess is that the .json files arent reading/writing correctly, resulting in an inventory that continually adds certain items to your file, without ever removing them when you drop them on the ground. Resulting in them "respawning" in your inventory on log in, when the game refreshes your inventory by checking the .json file.

**Comment by davidcernat** [comment]
Fixing this properly requires me to make a change to the PlayerInventory packet, but packet changes aren't something I can do as hotfixes because they break compatibility with existing builds, so I'll do that for 0.7.0-beta instead.

In the meantime, TES3MP/CoreScripts@1181860 is an OK band-aid. Apply it manually or download the prerelease again.

**Comment by Javimel** [comment]
Will do! A troubleshoot to it is also to simply remove the "copycat" items from your .json file directly, it can't add/copy items that no longer exist in your inventory file.

Simply put your items into a container, wait for a server save, and exit. Open up your characters .json file in notepad under /mp-stuff/data and delete the duplicating item(s) in {  } parentheses, making sure to remove any EXTRA commas as well. There should always be a comma immediately after a } followed by a space
    },

**Comment by davidcernat** [comment]
This should actually be fixed reasonably well now without the packet change I thought would be required, thanks to TES3MP/CoreScripts@be24a0f and related commits.
