### ISSUE TITLE
Aktwend not starting correctly

### ISSUE THREAD

**Issue by SallyMercury** [TES3MP/TES3MP#483]
Hi, 

The new tes3mp 0.7.0 Alpha works really well so far. I am just wondering, whether there is a way to make Arktwend to work. There is a Arktwend Mod for OpenMW 0.44 (https://www.nexusmods.com/morrowind/mods/45611) which works quite good. However if started in tes3mp, the character is falling down under Balmora, instead of starting on the Arktwend landmass. 

Second, tes3mp doesn't work very well with the Roscrea mod lore friendly version (https://www.nexusmods.com/morrowind/mods/45531), might be that the mod is not optimized by the mod author. If in buildings or caves the game works fine. But if two characters outside, the client player cannot move. Any ideas how to make it work correctly?

Keep up the awesome work. Cheers.

**Comment by StevenC21** [comment]
If those mods require complex scripting, they most likely won't work.

Specifically, MWSE scripting.

**Comment by StevenC21** [comment]
If those mods require complex scripting, they most likely won't work.

**Comment by davidcernat** [comment]
The default spawn position is the one that's suitable for regular Morrowind. Change it in your config.lua to account for different mods.

I don't see any connection between Arktwend and Roscrea not working properly. Please consider having separate issues for unrelated things.

**Comment by SallyMercury** [comment]
Dear David,

Changing the spawn position in the config.lua to "-10, 2", "-79136.9, 24318.5, 19.1162", "Forsaken Land", worked like a charm. Thanks a lot.

As for Roscrea, you are right, it is not related to Arktwend at all. I will wait until the Mod Author is updating his mod and then I will retry his lore friendly version in tes3mp again. Cheers
