### ISSUE TITLE
Docker 0.7.0 broken

### ISSUE THREAD

**Issue by droidman** [TES3MP/TES3MP#485]
If pull or build the official docker docker image I keep getting a error about the credits not being in the same folder as the executable. 

`Loading settings file: ./tes3mp-server-default.cfg
TES3MP dedicated server 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Commit hash: e834a4ec74
------------------------------------------------------------
[2018-11-15 09:13:27] [FATAL]: The server is shutting down
- To respect the hard work that has gone into creating TES3MP, you are
required to keep an unmodified tes3mp-credits file corresponding to this
version of the code in the same folder as this executable. It can have either
an .md or a .txt extension.`

**Comment by davidcernat** [comment]
What happens when you manually put the current version of tes3mp-credits.md there?

**Comment by GrimKriegor** [comment]
Hello there. Thanks for reporting this issue.

This should have fixed it:
https://github.com/TES3MP/server-docker/commit/58b236ebe8e84ec7078dcdba4a4ec3ccedce25ee

Btw, please keep future Docker image specific issues in:
https://github.com/TES3MP/server-docker/issues
