### ISSUE TITLE
Warning:: Picked up error in TriangleIntersect

### ISSUE THREAD

**Issue by divan4ik** [TES3MP/TES3MP#488]
OS: windows 10
Release verion: 0.6.2
Client: Steam Morrowind (licensed)
Plugins: [Morrowind|Bloodmoon|Tribunal].esm, morrowindonline.ESP
Effect: freeze loading forever

![bug](https://user-images.githubusercontent.com/3591619/48920762-d5e25b80-eeab-11e8-9faf-70cd175a8086.PNG)

**Comment by davidcernat** [comment]
Do you also get this problem in regular singleplayer OpenMW?

**Comment by davidcernat** [comment]
Sorry, I can't solve something that has no follow-up and that no one else has reported.
