### ISSUE TITLE
Azure's star does not store charges

### ISSUE THREAD

**Issue by street-grease-coder** [TES3MP/TES3MP#499]
Rather than a bug this is likely a missing feature. Get Azure's star, fill it with a soul, and the game will 'forget' what soul you captured after logout/login

**Comment by davidcernat** [comment]
Can you check that again after 76ac905efce6863f1a9867a661708fd802a3e8aa? The official Windows build for 0.7-alpha has already been updated.

**Comment by street-grease-coder** [comment]
thanks for the awesomly responsive quickfix, will do so asap, unfortunately that will likely take days/weeks

**Comment by davidcernat** [comment]
I haven't gotten any more reports of issues with soul gems, so I'm going to go ahead and close this.
