### ISSUE TITLE
Functions for inventory. Part 2

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#5]
_Originally posted by @Koncord_

| **Function** | **Status** | **Description** |
| --- | --- | --- |
| AddItem |  :heavy_check_mark: |  |
| RemoveItem |  :heavy_check_mark:   |  |
| GetItemCount |  |  |
| GetItemSlot |  | int GetItemSlot(int slot, char *item); // GetItemSlot return count and itemid. |

**Comment by Koncord** [comment]
closed by c27351c19e0fbbb7559559f35c2450fb73588005

**Comment by davidcernat** [comment]
Having two remaining stubs means this isn't really finished:

[UnequipItem](https://github.com/TES3MP/openmw-tes3mp/blob/c27351c19e0fbbb7559559f35c2450fb73588005/apps/openmw-mp/Script/Functions/Items.cpp#L39)
[GetItemCount](https://github.com/TES3MP/openmw-tes3mp/blob/c27351c19e0fbbb7559559f35c2450fb73588005/apps/openmw-mp/Script/Functions/Items.cpp#L77)

**Comment by Koncord** [comment]
Please, I want to fix it in weekend

**Comment by davidcernat** [comment]
Well, I want to contribute to this too so I can be able to implement it 100% correctly in the Lua scripts.
