### ISSUE TITLE
Compilation error: ‘RAKNET_STARTED’ is not a member of ‘RakNet’

### ISSUE THREAD

**Issue by marsmoon** [TES3MP/TES3MP#500]
I'm getting this error when trying to compile tes3mp 0.6.2 with CrabNet master:
```
[ 46%] Building CXX object apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Networking.cpp.o
In file included from CrabNet/include/raknet/RakNetTypes.h:20:0,
                 from openmw-tes3mp/./components/openmw-mp/Packets/BasePacket.hpp:5,
                 from openmw-tes3mp/./components/openmw-mp/Packets/PacketPreInit.hpp:9,
                 from openmw-tes3mp/apps/openmw/mwmp/Networking.cpp:12:
openmw-tes3mp/apps/openmw/mwmp/Networking.cpp: In constructor ‘mwmp::Networking::Networking()’:
openmw-tes3mp/apps/openmw/mwmp/Networking.cpp:180:18: error: ‘RAKNET_STARTED’ is not a member of ‘RakNet’
     RakAssert(b==RakNet::RAKNET_STARTED);
                  ^
CrabNet/include/raknet/RakNetDefines.h:89:29: note: in definition of macro ‘RakAssert’
 #define RakAssert(x) (void)(x);
                             ^
apps/openmw/CMakeFiles/tes3mp.dir/build.make:5942: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Networking.cpp.o' failed
make[2]: *** [apps/openmw/CMakeFiles/tes3mp.dir/mwmp/Networking.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:556: recipe for target 'apps/openmw/CMakeFiles/tes3mp.dir/all' failed
make[1]: *** [apps/openmw/CMakeFiles/tes3mp.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by street-grease-coder** [comment]
did you follow the official guide/steps posted by David?

**Comment by davidcernat** [comment]
You're not supposed to compile 0.6.2 with CrabNet. Use the pre-renaming RakNet that existed at the time.

**Comment by marsmoon** [comment]
@street-grease-coder
I couldn't find any compilation guide except the one that tells me to use tes3mp-deploy script.

@davidcernat
Where can I get that version? I can only find https://github.com/TES3MP/CrabNet.

**Comment by marsmoon** [comment]
Do you mean I'm supposed to use this https://github.com/facebookarchive/RakNet instead of the fork?

**Comment by davidcernat** [comment]
This is when TES3MP's fork of RakNet was renamed into CrabNet:

https://github.com/TES3MP/CrabNet/commit/1d6bb9e88db04aaeaa8752835c17574509d05a31

However, coming out as it did in December 2017, 0.6.2 did not include any TES3MP/RakNet commits after this one: https://github.com/TES3MP/CrabNet/commit/96db490e7e6bc503fa3cde56ac4fe48753a1ff30

I'm not really sure why you want to manually compile 0.6.2, though. There are official builds for it.

**Comment by marsmoon** [comment]
Thanks. I prefer to compile, because then I will be able to change stuff if I decide to.
