### ISSUE TITLE
Losing Permissions for TES3MP Files, tes3mp.exe Disappears After Each Session

### ISSUE THREAD

**Issue by alboboyo** [TES3MP/TES3MP#501]
I am running the 0.7.0 alpha on a Windows 10 machine, and my brother is running it on a Windows 8 machine. I boot up the tes3mp-server.exe without any issue, and we are able to play on a LAN connection using the tes3mp executable. However, after each gameplay session, tes3mp.exe is gone from its folder, and I lose permission to interact with the files in the folder (i.e. adding files to the folder). Upon trying to add files to the folder, Windows explorer displays a message that reads; "Destination Folder Access Denied: You need permission to perform this action." So, I cannot just copy another tes3mp.exe into the folder. 

![tes3mp error](https://user-images.githubusercontent.com/46404878/50728188-00067a80-10f4-11e9-9855-279e50595f6b.PNG)

Also, the folder becomes "Read-only", and if I go into its properties to change this, it reverts back to "Read-only" immediately after.

User Account Control is disabled on my system. I have also tried to add my user to the permissions manually through the Security tab in the folder Properties - this did not work either.

My brother, as a server client, has the same issue with permissions and the tes3mp.exe disappearing. 

I have worked around this problem by copying the contents of my tes3mp folder into a fresh install of the program, but this solution is a bit of a hassle since it has to be done every time we want to play. I would like to know if there is a more permanent fix.

**Comment by davidcernat** [comment]
Can you please explain where your tes3mp installation is located? Have you tried putting it somewhere else?

**Comment by alboboyo** [comment]
The tes3mp installation folder is located on my desktop screen. What would be a better location?

**Comment by davidcernat** [comment]
Can you try putting it in, say, C:\Games\tes3mp or D:\Games\tes3mp and see if that helps?

**Comment by alboboyo** [comment]
I put the folder in C:\Games\tes3mp, booted the server and tes3mp.exe, and it worked, but upon restarting my computer, tes3mp.exe was gone, and I lost permission to add files to the folder. The problem persists

**Comment by davidcernat** [comment]
Perhaps you have some overactive protection software. Try marking tes3mp.exe as safe in it.

**Comment by alboboyo** [comment]
Aha! It seems my Avast antivirus would quarantine tes3mp.exe every time I restart. I will make an exception for it. Thank you so much for your quick help. I am excited to enjoy more of your wonderful project!
