### ISSUE TITLE
casting chameleon on other player

### ISSUE THREAD

**Issue by RobertHolstein** [TES3MP/TES3MP#502]
I can cast chameleon on the player and they look see through from my point of view but they don't get the attribute and are not transparent from their view.

**Comment by davidcernat** [comment]
Are you casting on someone with high resistance to magic?

**Comment by RobertHolstein** [comment]
So it does work some times. I am guessing this has to do with the player's willpower? 

Though, if I cast the spell successfully and it doesn't take on the other players side he still ends up transparent for me.

**Comment by davidcernat** [comment]
Well, spell resistances are indeed not properly synchronized as of now. I guess I'll keep this open until they're fixed.
