### ISSUE TITLE
Consistant Crashing in Bloodmoon open world (server complete shutdown)

### ISSUE THREAD

**Issue by Nepsyneptune** [TES3MP/TES3MP#505]
Going north in Solstiem causes huge log spam (something to do with Wearwolves)
and bogs server down so much permanently that takes upwards of 5 mins to enter a room 
but usually the server  crashes before that leading to connection lost.
[tes3mp-server-2019-01-23-09_19_41.log](https://github.com/TES3MP/openmw-tes3mp/files/2786360/tes3mp-server-2019-01-23-09_19_41.log)

**Comment by davidcernat** [comment]
Can you please try again with a new download of the client, seeing as there was a recent hotfix for that kind of packet spam?

**Comment by Nepsyneptune** [comment]
still same issue after updating 
[tes3mp-server-2019-01-23-21_11_04.log](https://github.com/TES3MP/openmw-tes3mp/files/2788994/tes3mp-server-2019-01-23-21_11_04.log)

**Comment by Nepsyneptune** [comment]
soon as go north in solstiem (around where wolves and spriggens are)
server just spams untill it dies

**Comment by Nepsyneptune** [comment]
> Can you please try again with a new download of the client, seeing as there was a recent hotfix for that kind of packet spam?

yea still having same issue with it spamming until death (as soon as it starts game basically becomes unresponsive for all users (interacting with things no longer works)

**Comment by ghost** [comment]
I have explored most of Solstheim and didn't seem to be getting this packet spam issue as noted above.  

I have not done any quest related to Solstheim though

Running the latest version as of 03/25/19 [Win64 0.7 Pre-Release]

**Comment by davidcernat** [comment]
Yeah, I really have no idea what's going on here. @street-grease-coder, maybe you can elaborate?

**Comment by street-grease-coder** [comment]
unfortunately, I can't, haven't gone there (that's why I put the confused smiley). @Nepsyneptune, could this possibly be related to your content files? Are you using the original content *.bsd files?

**Comment by Nepsyneptune** [comment]
> unfortunately, I can't, haven't gone there (that's why I put the confused smiley). @Nepsyneptune, could this possibly be related to your content files? Are you using the original content *.bsd files?

Yes using Original Bsa files lol
tho was a modded run (cant remember if was rebirth or tamreil rebirth) lol
so maybe a conflict

**Comment by Veenkar** [comment]
Is Error.mdl OK for a player name?
Because that's what logs say during at the login.
> [2019-01-23 09:20:31] [INFO]: [Script]: Called "OnPlayerConnect" for pid 0
> [Script]: - New player is named Error.mdl
> [2019-01-23 09:20:31] [INFO]: System: Error.mdl (0) joined the server.

**Comment by Veenkar** [comment]
Also you are using a lot of non-vanilla content, which may not yet be compatible.
This can be be the rootcause.
Could you please try reproducing the issue with a fresh vanilla OpenMW install?

The logs listed the custom content you are currently using:
> - Morrowind.esm
> - Tribunal.esm
> - Bloodmoon.esm
> - Tamriel_Data.esm
> - TR_Mainland.esm
> - Morrowind Rebirth - Races [Addon].esm
> - TR_Factions.esp
> - Morrowind Rebirth [Main].ESP
> - Morrowind Rebirth - Mercenaries [Addon].ESP
> - Morrowind Rebirth - Game Settings [Addon].ESP
> - Morrowind Rebirth - Skills [Addon].ESP
> - Morrowind Rebirth - Birthsigns [Addon].ESP

**Comment by Nepsyneptune** [comment]
> Also you are using a lot of non-vanilla content, which may not yet be compatible.
> This can be be the rootcause.
> Could you please try reproducing the issue with a fresh vanilla OpenMW install?
> 
> The logs listed the custom content you are currently using:
> 
> > * Morrowind.esm
> > * Tribunal.esm
> > * Bloodmoon.esm
> > * Tamriel_Data.esm
> > * TR_Mainland.esm
> > * Morrowind Rebirth - Races [Addon].esm
> > * TR_Factions.esp
> > * Morrowind Rebirth [Main].ESP
> > * Morrowind Rebirth - Mercenaries [Addon].ESP
> > * Morrowind Rebirth - Game Settings [Addon].ESP
> > * Morrowind Rebirth - Skills [Addon].ESP
> > * Morrowind Rebirth - Birthsigns [Addon].ESP

Yes
It seems rebirth was the core issue
Whatever changes it made to the worldspace and enemies completly breaks tes3mp
Without rebirth it seems to works fine so far



Also yes a friend of mine is named error.mdl lmao

**Comment by Nepsyneptune** [comment]
So this can be safely closed o7

**Comment by davidcernat** [comment]
Nope, there shouldn't be problems like that in Morrowind Rebirth either.

**Comment by Veenkar** [comment]
I checked my vanilla version 0.7.1 and running around Soltsheim (including the north) works fine.

**Comment by Nepsyneptune** [comment]
> I checked my vanilla version 0.7.1 and running around Soltsheim (including the north) works fine.

Did you start the questline? 
Me and my friend where playing the quests when it happens lol 

I can say that after removing rebirth /tr it no longer happend for us (tho we did also start from scratch even redownloading  with new mods) 


So I'm still a bit confused lol
