### ISSUE TITLE
Missing Ground Geometry/Textures

### ISSUE THREAD

**Issue by HMGenzel** [TES3MP/TES3MP#507]
Non-multiplayer Morrowind runs with no issues. In all servers there is no ground geometry, no textures, and my cursor is not visible. I receive no errors and nothing seems unusual in the command line. 
![untitled](https://user-images.githubusercontent.com/47072922/51796717-4320ae80-21c5-11e9-9c24-ba1c60e8642d.png)

Screenshotting is behaving oddly, this strip of my screen is all I can grab.

OpenMW version 0.44.0
Retail CD Morrowind GOTY, English
Running clean install with no mods

**Comment by davidcernat** [comment]
Do you have OpenMW installed separately? Can you check if you get any problems in there?

**Comment by pcbeard** [comment]
I see a similar problem running on a Mac using tes3mp 0.7.0. The cursor is just a white box. Thje crosshair in the center of the screen is fine. This mainly happens when using menus.

**Comment by davidcernat** [comment]
The Mac issue is a separate one and is known to us. @Koncord will try to fix it when he does his next Mac builds.
