### ISSUE TITLE
Selling, buying back, and reselling an enchantable generated record to a merchant causes a server crash

### ISSUE THREAD

**Issue by Boyos999** [TES3MP/TES3MP#510]
Tested using a player enchanted armor and custom book record on up to date release and corescripts, steps to replicate:
-Sell an echantable generated record item to a merchant, causing the record and echantment record to be deleted from recordstore along with links
-Buy the item back from the merchant
-Sell the item to the merchant again, server crashes with the message: 
[2019-02-25 18:10:20] [ERR]: .\mp-stuff\scripts\recordstore\base.lua:47: attempt to index a nil value

**Comment by davidcernat** [comment]
Thank you for reporting this. The problem should be fixed after TES3MP/CoreScripts@ea2971a
