### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SallyMercury** [TES3MP/TES3MP#511]
Hi David,

I have only two suggestions to the awesome TES3MP and would like to know your feedback:

1. Would it be possible and logical to include Niapets Leveling Mod (https://www.nexusmods.com/morrowind/mods/42583) into TES3MP as a settings, because with multiple players the game becomes much easier.  And just changing the difficulty slider in the settings makes the enemies only weapon hit sponges? With this mod integrated, people can choose how quick they level up and how much the attributes multiplier will be.

2. I know you disabled the whole Census and Excise Office due to its issues with TES3MP and the whole character creation. However, isn't it possible to still activate the  Census and Excise Office without the tutorial and character creation scripts and make it as a normal building to visit,. Like after you return the tax record from the corpse to the Census and Exise Office. It should not be incompatable with TES3MP.

Thanks a lot. Keep up the great work.

Regards,
Sally

**Comment by street-grease-coder** [comment]
pre-answer first question:
1) difficulty level can be set by host in the config file I think. Mods can also be included by the host as desired

Also I wouldn't post suggestions here necessarily, this is thought to be more of a bug-tracker if I got this correctly...

**Comment by SallyMercury** [comment]
Hi, as I said I want to avoid difficulty slider or settings, because it makes the enemies to hit sponges. I wanted to  know whether if it's possible to integrate what the above mentioned mod does into TES3MP as a setting. That means you could choose to level up 2 or 4 times slower and change the attribute multiplier to 2 or even 1 in TES3MP itself. Without the mod installed.

Yeah you are right, this is more a bug-tracker here. Wrong place to put the suggestion. Sorry. :P

**Comment by Pop000100** [comment]
1. this I'd imagine isn't a matter for TES3MP, this a matter for plugins made with a Construction Set, considering David Cernat's(unsure about Koncord) view of OpenMW, this probably wont happen
2. contentFixer.lua contains the blocking code for the office, then you would just have to remove lines from default player creation in a plugin I'd think, unless I'm overlooking something.

edit: i just made a mod for this problem on the Nexus, if server owners don't want to make their own, it only allows access the the building not the actual character generation

**Comment by VicarIhon** [comment]
Hey, there is already a mod for bringing back the Census and Excise Office. It works flawless, just need to load the esp file and edit the content.Fixer.lua, after that the building is like in Vanilla. Check the posts tab on https://www.nexusmods.com/morrowind/mods/46485?tab=posts. Works like a breeze. Check it out guys. :p

**Comment by ghost** [comment]
there is also a lot of lua scripts for purpose of leveling, difficulty, chargen 
https://www.reddit.com/r/tes3mp/comments/c0njki/tes3mp_modding_guide/

**Comment by uramer** [comment]
There is also my own script to fix the game start and excise office https://github.com/tes3mp-scripts/OriginalStart

**Comment by ghost** [comment]
after we got the second and third option that did that.
just so there is a link to their first release here
https://www.nexusmods.com/morrowind/mods/45797

**Comment by davidcernat** [comment]
We're not going to include a leveling mod by default, since that's just silly.

However, the Census and Excise Office has been treated as a regular building since TES3MP/CoreScripts@a3495ff42c59c3012e49ba700c20e9453d42be00, so I'm going to go ahead and close this now.
