### ISSUE TITLE
Server on Raspberry Pi: libGL.so.1 not found

### ISSUE THREAD

**Issue by Hiradur** [TES3MP/TES3MP#525]
Hi,
I want to run a TES3MP server on a headless RPi2. On startup I get
`./tes3mp-server.armv7l: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory`
Is OpenGL really required to run the server?

**Comment by AokiAhishatsu** [comment]
Which Raspbian do you have?
Can you post your `uname -a`

**Comment by pongored81** [comment]
This is more of a question for the discord versus an issue, but a raspberry pi running Raspbian Stretch should only need the lua library to run. Otherwise you should be able to download the arm build and run it immediately

**Comment by Hiradur** [comment]
I run an up to date installation of Raspbian Stretch Lite. Here is the output of `uname -a`:
`Linux server 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

I just retried with the `tes3mp-server-GNU+Linux-armv7l-release-0.7.0-alpha-f6db7d4fc5-6cbaf2b517.tar.gz` release, the one I previously tested a few days ago was built on an older commit. Still the same error though.

> This is more of a question for the discord versus an issue

I wasn't sure if the error was caused by an unwanted dependency which slipped in.

**Comment by 1338** [comment]
Are you still facing this issue?

I did some testing on an RPi3 and didn't have any need for libs except the luajit. The server shouldn't need openGL.

**Comment by Hiradur** [comment]
I retried today with `
tes3mp-server-GNU+Linux-armv7l-release-0.7.0-alpha-023ead937f-13c992ede6.tar.gz ` but the problem persists. Are you using the desktop image rather than the lite image to test? OpenGL might be preinstalled there which could explain why you don't see this error.

As far as I can tell the server binary is linked against libGL:
```sh
readelf -d tes3mp-server.armv7l 

Dynamic section at offset 0x3d3ec0 contains 36 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libluajit-5.1.so.2]
 0x00000001 (NEEDED)                     Shared library: [libdl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libboost_system.so.1.62.0]
 0x00000001 (NEEDED)                     Shared library: [libboost_filesystem.so.1.62.0]
 0x00000001 (NEEDED)                     Shared library: [libboost_program_options.so.1.62.0]
 0x00000001 (NEEDED)                     Shared library: [libGL.so.1]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
```

I don't seem to have libGL installed:
```
ldconfig -p | grep libGL
	libGLESv2.so (libc6,hard-float) => /opt/vc/lib/libGLESv2.so
```

I suppose I could install the OpenGL driver through `raspi-config` but if OpenGL is not needed for the server removing it as a dependency is probably the better way.

**Comment by Hiradur** [comment]
Installing the GL driver via `raspi-config` did not help, but installing `libgl1` did.
