### ISSUE TITLE
The enchanted mace Scourge causes crash when cast

### ISSUE THREAD

**Issue by thefuzz45** [TES3MP/TES3MP#528]
The unique mace Scourge found in tel fyr has the ability to conjure a dremora and a scamp. When i try to summon them my game crashes every time. It freezes, I hear the summoning sound but my only option is to close program.

I thought maybe the necromancer amulet i was wearing might cause an issue because of the spell absorption but it crashes with it off as well.

**Comment by davidcernat** [comment]
Thanks for pointing that out. It seems abc4090a0fe1e0cc04cef598a598744d53f3ef6f has fixed your problem.
