### ISSUE TITLE
Error when generating with Cmake 3.14.5

### ISSUE THREAD

**Issue by simkej** [TES3MP/TES3MP#530]
An error appears when trying to generate project files from the source. This error is not present when trying to generate with latest openmw source but is present in older openmw releases.

`CMake Error at CMakeLists.txt:224 (get_filename_component):
  get_filename_component unknown component
  C:/OpenMW-dev/openmw/MSVC2017_64/deps/OSG/lib/osgDB.lib`

As far as I know I can't generate project files with this error present.

**Comment by testman42** [comment]
This repo is for TES3MP, which is fork of OpenMW.
There are few ways you can report this more directly to OpenMW developers:

- Start a thread in [support section of OpenMW forum](https://forum.openmw.org/viewforum.php?f=8)
- Create a new issue in [OpenMW repo on GitLab](https://gitlab.com/OpenMW/openmw)
- Join [#openmw IRC channel](https://webchat.freenode.net/?channels=openmw&uio=OT10cnVlde) or [OpenMW Discord server](https://discord.gg/wd3eSas)

**Comment by simkej** [comment]
I managed to fix the issue myself.

**Comment by testman42** [comment]
![image](https://i.redd.it/7khgt29lp1121.jpg)

@Sallad02 Would you then be so kind as to describe where you found the solution or how you managed to fix the issue, so that other people who with same problem who come across this thread might be pointed in the right direction?

**Comment by simkej** [comment]
I added the changes from the following commit from the openmw repo.

https://github.com/OpenMW/openmw/commit/9067731a96cb83702b25f69677afba1d209cb9d4#diff-af3b638bc2a3e6c650974192a53c7291
