### ISSUE TITLE
Freeze components versions?

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#531]
Hi @davidcernat 
We have a package for tes3mp in NixOS https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/openmw/tes3mp.nix

The problem with updating it is that its unknown which exact revisions of dependencies were used to build an official package at https://github.com/TES3MP/openmw-tes3mp/releases And we like to match official package.

Could you please note revisions of each dependency somewhere next time you'll make a new release? Thanks

**Comment by GrimKriegor** [comment]
Hello there.

NixOS... honestly I have been eyeing it for a few years now. Looks just like my kind of thing. The strongest candidate for a migration from Parabola, ahah.

These are the current revisions of each dependency used to build the official packages.

TES3MP: Latest from the current stable branch (0.7.0 atm)
CoreScripts: ditto
CallFF: *deprecated*
CrabNet: [4eeeaad2f6c11aeb82070df35169694b4fb7b04b](https://github.com/GrimKriegor/TES3MP-deploy/blob/master/tes3mp-deploy.sh#L589)
Bullet: [2.86](https://github.com/GrimKriegor/TES3MP-deploy/blob/master/tes3mp-deploy.sh#L578)
GCC: [6.4.0](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L23)
CMake: [3.5.2](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L42)
Boost: [1.64.0](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L49)
MyGUI: [82fa8d4fdcaa06cf96dfec8a057c39cbaeaca9c](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L70)
OSG: [3.4](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L86)
Qt: [5.5](https://github.com/GrimKriegor/TES3MP-forge/blob/master/Dockerfile#L104)

For reference, here are the environment and build scripts:
https://github.com/GrimKriegor/TES3MP-forge
https://github.com/GrimKriegor/TES3MP-deploy

Let us know if there is something else we can help with.

**Comment by ghost** [comment]
@GrimKriegor Thank you much for the answer!
So looks like I done it right except CrabNet revision.
And thanks for the tes3mp-deploy :smile:

**Comment by ghost** [comment]
@GrimKriegor 
> TES3MP: Latest from the current stable branch (0.7.0 atm)

Hm, what about releases?

**Comment by GrimKriegor** [comment]
I should have been more specific.

Whenever the developers want a new release they manually trigger the build process, which pulls the code from the desired version branch, 0.7.0 at the moment.

I don't think its guaranteed those branches are buildable all the time, so relying on the tags is probably a better idea https://github.com/TES3MP/openmw-tes3mp/tags

Hope this makes sense.

**Comment by gnidorah** [comment]
@GrimKriegor 
I see most of public servers use latest but a bit old release 0.7.0-alpha https://github.com/TES3MP/openmw-tes3mp/commit/292536439eeda58becdb7e441fe2e61ebb74529e
Do you now which versions of these components are used for them?
- RakNet / CrabNet
- CallFF (still required for that release)
- CoreScripts

**Comment by ghost** [comment]
@GrimKriegor Thanks again! https://github.com/GrimKriegor/TES3MP-deploy gave me understanding what versions should I use
