### ISSUE TITLE
Miscellaneous Quests that add Faction Rep add you to that faction erroneously

### ISSUE THREAD

**Issue by singularity125** [TES3MP/TES3MP#533]
Playing this with a friend of mine and shared quest progression on a private self-hosted server, we're wandering around Khuul and completed a miscellaneous quest:
https://en.uesp.net/wiki/Morrowind:Kidnapped_by_Cultists

My friend noted the guy mentioned house Redoran and well, I checked my menu afterwards to find that we were now "Hirelings" in House Redoran. This is especially problematic since we are already in House Telvanni.

This happened once before with some unknown quest placing us in the Imperial Legion faction and not realizing the issue until they got stuck on a broken record about non-existant uniforms... Luckily the workaround is simple, remove the faction rep from the world.json, but I rather like this aspect of Morrowind where you can do a few side tasks without actually joining some guilds, and it'd be nice to keep the rep. Ranks are in a separate list in the json right above and there's still no listed redoran rank there, yet it seems to default to the lowest rank ingame if it sees rep.

**Comment by Veenkar** [comment]
I think I found something in LocalPlayer.cpp.
In function setFactions(), there is this fragment with a comment:
`// If the player isn't in this faction, make them join it`
I guess this has to be removed, and the check needs to be performed before adjusting a faction rank in the while loop below.

**Comment by davidcernat** [comment]
Good point. I'd forgotten about that.
