### ISSUE TITLE
TES3 MP server error messages

### ISSUE THREAD

**Issue by PCsaba1979** [TES3MP/TES3MP#535]
Hi,

Whenever I start the server, I get error messages, which seem to vary:

![error message 1](https://user-images.githubusercontent.com/54170309/63153124-ddcfc600-c00d-11e9-8e79-c71b50b53d7d.jpg)
![error message 2](https://user-images.githubusercontent.com/54170309/63153128-df998980-c00d-11e9-9f9c-6e2cc88d6f1a.jpg)
![error message 3](https://user-images.githubusercontent.com/54170309/63153129-e1fbe380-c00d-11e9-8de5-bfe1100f433b.jpg)
![error message 4](https://user-images.githubusercontent.com/54170309/63153134-e3c5a700-c00d-11e9-9d0c-2813dd181031.jpg)

If I start the server, I get an error message, then I close the window, restart, and get another -usually different - error message. My server settings:

[General]
# The default localAddress of 0.0.0.0 makes the server reachable at all of its local addresses
localAddress = 192.168.0.175
port = 25565
maximumPlayers = 2
hostname = TES3MP Server
# 0 - Verbose (spam), 1 - Info, 2 - Warnings, 3 - Errors, 4 - Only fatal errors
logLevel = 0
password = semmi

[Plugins]
home = ./server
plugins = serverCore.lua

[MasterServer]
enabled = false
address = master.tes3mp.com
port = 25561
rate = 10000

The strange thing is that in February never had such an issue. If any can help, I appreciate that. I'm sorry if it was not the right place to post this. If so, please redirect me. Thank you

**Comment by davidcernat** [comment]
Those error messages are a false alarm. Disregard them. There was simply a typo in Koncord's io2 input/output library causing CJSON to sometimes not read JSON files correctly, but it's fully replaced by dkjson whenever that happens. Your server works fine otherwise.
