### ISSUE TITLE
Lua API function to reset the DataFiles list

### ISSUE THREAD

**Issue by JakobCh** [TES3MP/TES3MP#538]
Doesn't seem to be any way to remove registered DataFiles after you add them with "tes3mp.AddDataFileRequirement", or maybe calling tes3mp.SetDataFileEnforcementState(false) already does that?

**Comment by davidcernat** [comment]
tes3mp.SetDataFileEnforcementState(false) makes it so the list of data files isn't enforced at all.

What use case did you have in mind for removing data files from the list?

**Comment by JakobCh** [comment]
Well really I just wanted some way to replace the OnRequestDataFileList serverCore.lua function but I thought having some way to change the data files of the server on the fly might be good

**Comment by davidcernat** [comment]
I need a use case.

My current thinking is that, if there are still players on the server, it's weird removing a requirement for one of the data files they currently have enabled. If there are no players on the server, then it does little harm to restart the server so it can have the new list of required data files.

**Comment by JakobCh** [comment]
I was thinking that you could kick everyone and then change the data files without restarting the server.
But yeah you're right there's probably no reason to do that instead of a restart.

**Comment by slowpokefarm** [comment]
The only good reason to avoid restarts is to keep disposition data for players, if it’s still an issue in latest versions.

**Comment by uramer** [comment]
But you would have to kick all the players anyway, so they will lose their disposition data (and merchant stocks, and whatever else isn't stored on the server yet)

**Comment by JakobCh** [comment]
Okey I'm closing this, made a pull request to get a hook on OnRequestDataFileList so we can override the data files at server launch atleast https://github.com/TES3MP/CoreScripts/pull/84
