### ISSUE TITLE
Linux (manjaro) client cant use chat /reg or /login with its own server

### ISSUE THREAD

**Issue by Pollito001** [TES3MP/TES3MP#54]
I compiled using install.sh script but when i run the server just let me put the name and nothing more.

**Comment by davidcernat** [comment]
You need to add the Lua scripts from https://github.com/TES3MP/PluginExamples to your tes3mp installation.

After that, open up your tes3mp-server-default.cfg and make this line point towards the folder containing your scripts subfolder:

`home = ~/ClionProjects/PS-dev`

For instance, I turn it into this:

`home = ./mp-stuff`

Also change this line from this:

`plugins = tes3mp.lua,chat_parser.lua`

Into this:

`plugins = server.lua`

That will add the missing functionality to your server.

**Comment by Pollito001** [comment]
My tes3mp-server-default.cfg is fine , when i run server then launch tes3mp ask my name when i enter my name the server detect im connect but i cant write in the chat or hide/show chat with f2 or Y nothing happens just kick me after 60 sec

**Comment by Koncord** [comment]
Very strange! I use Linux Mint (based on Ubuntu) and all fine for me. My friend tested tes3mp on Debian, fine too.

**Comment by Koncord** [comment]
I will write simple SDL test later.

**Comment by Pollito001** [comment]
ok, thanks for the help, Im using Manjaro (based on Archlinux).

**Comment by Pollito001** [comment]
I use free video driver Gallium 0.4.

**Comment by Yaksinikos** [comment]
Confirmed bug
My specs;
Linux Mint 18.1
Morrowind GOTY (german)
Russian key-layout.

**Comment by Koncord** [comment]
Maybe fixed by b9c3849cc7a20e9e5968fce2495ba072a8dfabd7
@Translator5 can you confirm?

**Comment by Yaksinikos** [comment]
@Koncord nope, do not look like it works. :(

**Comment by Koncord** [comment]
I think this bug is fixed.
