### ISSUE TITLE
Failed to create graphics context

### ISSUE THREAD

**Issue by Chryseus** [TES3MP/TES3MP#542]
Version 0.7-alpha fails to create graphics context, newer versions of openmw work just fine.
Running on Arch Linux.

[error.txt](https://github.com/TES3MP/openmw-tes3mp/files/4093380/error.txt)
[glxinfo.txt](https://github.com/TES3MP/openmw-tes3mp/files/4093384/glxinfo.txt)

**Comment by HadetTheUndying** [comment]
I'm getting this same issue. And Building from Source fails 100% of the time. Void Linux here

**Comment by govai123** [comment]
Same problem here on Arch Linux.

**Comment by HadetTheUndying** [comment]
So what I ended up doing was compiling from source and taking the version file from the release and dropping it in my compiled version. Probably has to do with the forge docker vcontainer using an older version of Debian to build the release

**Comment by jtuu** [comment]
Here's a workaround: remove the libstdc++ files from your tes3mp/lib directory.
