### ISSUE TITLE
difficulty with A.I.... Receiving too much aggro in co-op!

### ISSUE THREAD

**Issue by Dafarkias** [TES3MP/TES3MP#548]
playing co-op, and for some reason I'm receiving an unrealistic amount of aggro. I'm playing a mage that wields a bow and even if I'm not attacking an enemy creature, it will actively chase me around even while my fighter friend attacks and damages the creature with close combat. 

I'm using .7, I'm hosting and admin, if that matters. Oh, and I've barely added mods or made any config adjustments. The only mods I've added are very small, that have nothing to do with A.I. (as far as I know).

I freakin' love this project.

Please help!!

**Comment by davidcernat** [comment]
Aggro is a concept from other video games. In Morrowind and OpenMW, enemies go after the most vulnerable target instead, which happens to be you.

**Comment by Dafarkias** [comment]
Okay.

Is it something that I can alter or configure? I have a basic knowledge of
programming, and a fairly good familiarity with Lua.

It makes sense to me as a concept, except the fact that once there's a
person attacking and damaging the creature at close combat it would turn
its attention to that person. That's natural instinct.

It would be more likely for a humanoid enemy to run from a fight if they
didn't want to fight a fully armor suited combatant then to think "oh I'll
just kill his comrade the whole while he's hacking a sword into the back of
my neck."

Just something to think about buddy.

**Comment by davidcernat** [comment]
It was always assumed that the serverside scripts would someday allow you to change how the AI works in situations like that, but the project simply never got that far.

**Comment by Dafarkias** [comment]
Hmmmm.

Does that mean the project is abandoned or on hiatus?

**Comment by Dafarkias** [comment]
Digging through all (most) the lua files and for the life of me, I can't seem to find anything relating to enemy combatants choosing their targets.

Any help would be appreciated!

**Comment by testman42** [comment]
LUA files contain server-side logic. NPC AI is client side at the moment. The authority player tells server what the NPCs are doing and the server relays that to other players.

**Comment by uramer** [comment]
To change NPC behaviour you would have to alter OpenMW AI
Currently it just goes for whichever target is easiest to hit, which is usually squishy mages
If you want to be ignored by the AI, invest into a lot of Agility and/or Sanctuary, and ask your melee to do the opposite

**Comment by Dafarkias** [comment]
Understood. Of course, with a low Agility the melee would rarely every land a hit. 

Is it realistic that someone with minimal (basically none) c++ experience would be able to mod the AI in OpenMW? 

Where's the first place I should dig into if it were something I could handle?

**Comment by Dafarkias** [comment]
I'm not trying to reinvent the wheel here... but imagine this scenario in a co-op situation:

co-op players, 1 melee tank, 1 ranged mage.

3 npc enemies. 

co-op players enter dungeon room. mage is trailing the fighter at a distance where the NPC's can barely even see him. 

fighter begins to attack 1 of the NPC's. mage starts to cast a conjure spell. 

all 3 NPC's run full sprint past the fighter and begin to chase the mage. 

mage has no choice but to stop casting spells and run for his life in circles around the dungeon room. 

Conclusion?

you have a fighter trying to whack away at 3 psychopaths full sprinting after a mage who only ever got to cast 1 conjuration spell, and never even drew blood from the assailants.

**Comment by testman42** [comment]
I would argue that such thing is a challenge that you could solve by changing your strategy rather than changing the way AI behaves.
Assess the situation before you engage. Deepen your understanding of game mechanics. Know how far away you must remain in order to not get attacked. If you expect combat, have mage do the conjuring before fighting starts. Invisibility can be used in order to have attackers lose sight of their current target, making them go fight next viable target.

**Comment by Dafarkias** [comment]
Idk how else to explain it. It feels very primitive (almost buggy). I got what you are saying that _this is morrowind, it's not supposed to be like other games_--but it should be playable, right? Idk if any of you have actually tried playing co-op and encountered a situation like I've been describing, but I doubt you'd like it either. 

Obviously I realize that this issue stems from playing co-op in a game designed single player using an unfinished project. I'm not stupid (sometimes).

My beef is that let's say I added a server 'cheat' where if a player were playing a mage, he would receive a large boost to Agility to ensure that he didn't draw _ALL_ the aggro. The issue is that if that mage wanted to be a hybrid archer, his marksmanship would be off-the-charts.

**Comment by Dafarkias** [comment]
Also, would any of you gentlemen be so kind to point me in the direction of a resource or code example on how to add a simple timed function script onto my server? For instance, let's say I want to run a console command every second... I'm digging through other TES3MP scripts but have had no luck yet.

**Comment by testman42** [comment]
running console commands can be done in two ways:
1. by admin with in-game commands. Here is the description of relevant commands:
`/storeconsole <pid> <command>`
Store a certain console command for a player
`/runconsole <pid> (<count>) (<interval>)`
Run a stored console command on a player, with optional count and interval in miliseconds
2. with LUA server scripts
Here is an example of such line:
`logicHandler.RunConsoleCommandOnPlayer(pid, "player->additem potion_skooma_01")`
where `pid` is the variable that holds a valid player ID of type integer.

**Comment by Dafarkias** [comment]
Ty!

So if you don't mind me furthering my question:

What if I'm specifically trying to incorporate magicka regen onto my server instead of asking each of my comrades to install a mod on their pc. 

Where would the most ideal location to insert a snippet of code that iterates through all server players every certain interval and increases their magicka?

**Comment by Learwolf** [comment]
You could either make a custom record spell that regenerates magicka, and force it upon all players on character creation (As low as 1 magicka per second this way), or another more tedious method would be to create a timer on the server that regenerates x magicka every y second(s). For assistance, you can visit the tes3mp official discord and ask for help (in the scripting_help section) there instead of here https://discord.gg/xJxSPN

**Comment by Dafarkias** [comment]
Ty!

**Comment by davidcernat** [comment]
> Hmmmm. Does that mean the project is abandoned or on hiatus?

I don't see how one would follow from the other. The fact that not everything imaginable is implemented doesn't mean the project isn't still in development.

**Comment by Dafarkias** [comment]
"...but the project simply never got that far" -davidcernat

I realize you didn't explicitly _say_ the project was no longer in development, but that statement you made ^ infers it. At least in English. 

"the project has not gotten that far yet"

**Comment by Dafarkias** [comment]
Created a custom script where a mage character gets an automatic sanctuary buff when in the vicinity of his party. This makes the aggro draw much more balanced (in my personal opinion).

**Comment by katuwiran** [comment]
> Created a custom script where a mage character gets an automatic sanctuary buff when in the vicinity of his party. This makes the aggro draw much more balanced (in my personal opinion).

Is there a chance you will share the code publicly? Me and my friends might need something like that
