### ISSUE TITLE
MacOS version does not start

### ISSUE THREAD

**Issue by SallyMercury** [TES3MP/TES3MP#551]
Dear David,

Thank you for your awesome Morrowind Multiplayer. It works very well on Linux and Windows. But unfortunately I have not figured out, how to run tes3mp and change config files in Mac OS. The tes3mp DMG file if installed only starts the tes3mp Browser. And if I mount the DMG file and go in a terminal to /Volumes/TES3MP-0.7.0-Darwin/TES3MP.app/Contents/Resources, I cannot edit the tes3mp-client-cfg file to add the IP address of my friends Linux server over LAN, because the image is write protected. Although tes3mp starts if started from the terminal under /Volumes/TES3MP-0.7.0-Darwin/TES3MP.app/Contents/MacOS/ 
How to use the Mac Version of TES3MP? Thanks a lot.  

Regards, Sally

**Comment by testman42** [comment]
Aren't you supposed to copy contents of the mounted volume to somewhere on your disk and run from there? That's how most DMG images work. Firefox for example, has an illustration that indicates what user should do.
![firefox](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2020-02-04-03-15-35-ee0dc6.png)
Sadly TES3MP container does not have such image.

**Comment by SallyMercury** [comment]
Hi Testman42,

Yes, I did install it with dragging the tes3mp app icon into the Application folder. However if I start tes3mp from MacOS Launchpad after that, only the tes3mp browser window is opening up. But I wanna start the game with the tes3mp command inside the dmg file and change the config file to add the IP of my buddy's laptop to connect to his tes3mp-server via LAN. That would only work if I had write access to the mounted TES3MP-0.7.0-DARWIN.dmg file. 
Is it possible to extract the game file just as in Linux? Like just extract the dmg file as a folder and start the program or change config files via terminal?
If I extract the dmg file with "7z l tes3mp.dmg" I get its content, but under Linux I get TES3MP-0.7.0-Darwin/TES3MP.app/Content and all files below, but under Mac OS I only get TES3MP. Seems like the OS does not let me get into the app file. Any ideas?

**Comment by SallyMercury** [comment]
> Aren't you supposed to copy contents of the mounted volume to somewhere on your disk and run from there? That's how most DMG images work. Firefox for example, has an illustration that indicates what user should do.
> ![firefox](https://camo.githubusercontent.com/384ff2438321d55d0d8bfc6ebf9627d751e9135d/68747470733a2f2f757365722d6d656469612d70726f642d63646e2e69747372652d73756d6f2e6d6f7a696c6c612e6e65742f75706c6f6164732f67616c6c6572792f696d616765732f323032302d30322d30342d30332d31352d33352d6565306463362e706e67)
> Sadly TES3MP container does not have such image.

Thank you very much. After mounting the dmg file I have to click right mouse click > Show content then copy it to my document folder and it worked flawlessly :)

**Comment by SallyMercury** [comment]
Hi testman42, now a new problem popped up. If I start the game via /Users/sallymercury/Documents/TES3MP-0.7.0-Darwin/MacOS/tes3mp it starts with all mods but everything is in pink because the program can't readwrite DDS file. It seems tes3mp has no access to the folder /Users/sallymercury/Documents/TES3MP-0.7.0-Darwin/PlugIns/osgPlugins-3.4.1. So the DDS texture files can't be loaded. How to fix this?

**Comment by testman42** [comment]
@SallyMercury I just went to check if game works for me, and I did not encounter the issue that you describe.
However, I suspect that the problem comes from the way you copied TES3MP to your PC.
Would you be so kind as to try again, but this time after you mount the DMG open it in a window. So that it looks like this:
![tes3mp](https://i.imgur.com/2M9gq8A.png)
Then drag and drop the TES3MP icon on the Applications icon.
After that is done, find the now newly created TES3MP icon in your list of applications, run it and join some public server. Just to see if colours are all right now.
You should still be able to right-click on it and access it's contents, for when you want to run the TES3MP directly instead of the server browser.
Do report if you manage to get it to work properly :+1:

**Comment by SallyMercury** [comment]
Yes that did the trick. Thank you very much for your fast help!
