### ISSUE TITLE
Server crash from script error

### ISSUE THREAD

**Issue by Cubeson** [TES3MP/TES3MP#553]
Server crashed right after unequipping steel tanto, the item itself is propably meaningless 

Full log
[tes3mp-server-2020-06-05-15_38_22.log](https://github.com/TES3MP/openmw-tes3mp/files/4736417/tes3mp-server-2020-06-05-15_38_22.log)

3 last lines are most interesting
[2020-06-05 15:34:29] [INFO]: [Script]: Called "OnPlayerEquipment" for Roktil (0)
[2020-06-05 15:34:29] [ERR]: .\server\lib\lua\tableHelper.lua:162: bad argument #1 to 'pairs' (table expected, got nil)
[2020-06-05 15:34:29] [ERR]: [Script]: Server crash from script error

**Comment by Cubeson** [comment]
Server crashes after creating new character aswell

[tes3mp-server-2020-06-05-16_16_23.log](https://github.com/TES3MP/openmw-tes3mp/files/4736649/tes3mp-server-2020-06-05-16_16_23.log)

**Comment by davidcernat** [comment]
Let me guess. You've edited config.lua and made a mess out of this line:

`config.bannedEquipmentItems = { "helseth's ring" }`

For reference, this is how you empty it:

`config.bannedEquipmentItems = {}`

You can see that by scrolling down in the file and seeing other lines like these:

```
config.disallowedCreateRefIds = {}
config.disallowedLockRefIds = {}
config.disallowedTrapRefIds = {}
config.disallowedStateRefIds = {}
```

**Comment by Cubeson** [comment]
yeah, I assumed it would work like skyrim's .ini files and assume a default value if a line doesnt exist

**Comment by davidcernat** [comment]
No, it's not the same file format at all.

Anyway, is your problem resolved now?

**Comment by Cubeson** [comment]
yes
