### ISSUE TITLE
Merchants' inventory synchronization

### ISSUE THREAD

**Issue by Sarevalak** [TES3MP/TES3MP#554]
Is it possible to implement synchronization of merchants' inventory? It will allow to avoid power gaming and improve gaming experience.

---

Sorry for my bad English, but i am not native speaker.

**Comment by davidcernat** [comment]
It's implemented as of 27b93574789b47179cc0fefaf0e366bcbb3bdf83 and 975797c09b1b5f213c1b43b8f1a6e22a5b70bae6.
