### ISSUE TITLE
0.7.0 branch fails to build with mygui 3.4.0

### ISSUE THREAD

**Issue by ghost** [TES3MP/TES3MP#555]
After updating `mygui` dependency from 3.2.2 to 3.4.0 `tes3mp` fails to build (using latest commit in 0.7.0 branch) .
`openmw` had the same issue in 0.45.0 release, but it got fixed with 0.46.0 release

**Comment by uramer** [comment]
Well, this is expected. 0.7 is based on roughly 0.45.
I suspect the 0.7.1 branch doesn't have the same issue, as it includes most of (if not all) 0.46 commits
