### ISSUE TITLE
Server crashes immediately (nil value)

### ISSUE THREAD

**Issue by Rafaeltheraven** [TES3MP/TES3MP#557]
Using Debian 10, I used to be able to run the tes3mp server but for some reason am no longer able to.
Using a fresh 0.7-alpha x64 install gotten from the releases page, I get the following error trying to run `./tes3mp-server`:
```
Loading server config from the package directory
Loading settings file: ./tes3mp-server-default.cfg
TES3MP dedicated server 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Oldest compatible commit hash: 292536439e
------------------------------------------------------------
[2020-06-21 13:50:59] [ERR]: Lua script ./CoreScripts/scripts/serverCore.lua error (2): "./CoreScripts/lib/lua/jsonInterface.lua:9: attempt to call field 'encode_empty_table_as_object' (a nil value)"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Lua script ./CoreScripts/scripts/serverCore.lua error (2): "./CoreScripts/lib/lua/jsonInterface.lua:9: attempt to call field 'encode_empty_table_as_object' (a nil value)"
./tes3mp-server: line 7: 31489 Aborted                 LD_LIBRARY_PATH="./lib" ./tes3mp-server.x86_64 "$@"
```

If I try to run `./tes3mp-server.x86_64` I get:
```
./tes3mp-server.x86_64: error while loading shared libraries: libboost_system.so.1.64.0: cannot open shared object file: No such file or directory
```
These same issues occur when trying to use the `tes3mp-deploy` script.

**Comment by davidcernat** [comment]
It looks like you've installed lua-cjson on your system, so the TES3MP server is trying to use it, but it actually needs extra functions from one here that's based on the OpenResty fork of lua-cjson:

https://github.com/TES3MP/lua-cjson

Just open up your server/lib/lua/jsonInterface.lua and turn this line:

    local cjsonExists = doesModuleExist("cjson")

Into:

    local cjsonExists = false

**Comment by Rafaeltheraven** [comment]
That was it, thanks! For me the file was in `./CoreScripts/lib/lua/jsonInterface.lua` but changing the line fixed it!
