### ISSUE TITLE
crashes when i enter a building

### ISSUE THREAD

**Issue by sathendron** [TES3MP/TES3MP#561]
the game crashes saying I lose connection

**Comment by davidcernat** [comment]
What does the server log say?

**Comment by sathendron** [comment]
it closes the server when I enter a building so I don't get to check however I just now saw an error saying 
[Script]: Could not find Lua CJSON! The decoding and encoding of JSON files will always use dkjson and be slower as a result. Idk if it has any relevance

**Comment by testman42** [comment]
that is of no relevance
if server crashes, then the last log should show an error of what went wrong.
Best if you put whole log in Pastebin or some alternative to it (or make [gist](https://gist.github.com/)) and link it here.

**Comment by davidcernat** [comment]
This was never followed up on, so I'm closing it.
