### ISSUE TITLE
Can't start server.

### ISSUE THREAD

**Issue by Katayo0** [TES3MP/TES3MP#570]
When I try to start server, it always says:"Cannot connect to master server"
![unknown](https://user-images.githubusercontent.com/53634824/97169668-c5d90200-17cd-11eb-9cb8-0e24389e4483.png)

**Comment by testman42** [comment]
That is usually just a temporary problem. Even if that happens, your TES3MP server is still working fine. You can connect to it and other people can establish direct connection to it as well.
Did you check if your server really doesn't show up in the server browser? If the issue persists, you will be able to get most support in #technical_help on TES3MP Discord server.
