### ISSUE TITLE
 game freezes in "loading area"

### ISSUE THREAD

**Issue by Alam188** [TES3MP/TES3MP#571]
I have problems with tes3mp, what happens is that when I open a server, the game loads the expansions and everything is normal, but when it reaches "loading area" the game freezes just after loading the bar and I get the warning " tes3mp stopped working. " Thanks for your attention.
[tes3mp-client-2020-11-07-15_56_28.log](https://github.com/TES3MP/openmw-tes3mp/files/5506916/tes3mp-client-2020-11-07-15_56_28.log)

**Comment by Alam188** [comment]
[tes3mp-client-2020-11-07-14_31_28.log](https://github.com/TES3MP/openmw-tes3mp/files/5506922/tes3mp-client-2020-11-07-14_31_28.log)
this is another crash, which i saw was different from the previous one, and i sent it just in case

**Comment by Alam188** [comment]
[tes3mp-client-2020-11-07-14_31_28.log](https://github.com/TES3MP/openmw-tes3mp/files/5507015/tes3mp-client-2020-11-07-14_31_28.log)

this is another crash different from the previous one but it is the same problem

**Comment by davidcernat** [comment]
I remember someone having a similar problem after making changes to their OpenMW saves folder at C:\Users\Username\Documents\My Games\OpenMW\saves

Can you try moving out the subfolders from it to see if it helps?

**Comment by Alam188** [comment]
the saves folder is empty. 
it's the first time i try to play

**Comment by davidcernat** [comment]
Does regular OpenMW 0.45, as installed separately in its own folder, work fine for you?

Get it from here:

https://github.com/OpenMW/openmw/releases/download/openmw-0.45.0/OpenMW-0.45.0-win64.exe

**Comment by Alam188** [comment]
thanks i will try to install it to see if it works

**Comment by Alam188** [comment]
Is that version for 64-bit windows? I have a 32-bit version, won't there be a 32-bit version?

**Comment by Alam188** [comment]
Sorry, I've been looking for a solution to the problem, but I can't find it. Could someone pass me the download link of a tes3mp compatible morrowind? I think it's my version of the game, that although it has all the expansions I get the following warning:
![Morrowind 2020-11-17 18-53-20-348](https://user-images.githubusercontent.com/74149930/99460494-52c33700-2906-11eb-91c2-6f7a7ad76447.jpg)

**Comment by Alam188** [comment]
I think that's why

**Comment by testman42** [comment]
[Morrowind GOTY on GOG](https://www.gog.com/game/the_elder_scrolls_iii_morrowind_goty_edition)
[Morrowind GOTY on Steam](https://store.steampowered.com/app/22320/The_Elder_Scrolls_III_Morrowind_Game_of_the_Year_Edition/)

**Comment by Alam188** [comment]
thanks

**Comment by davidcernat** [comment]
> Could someone pass me the download link of a tes3mp compatible morrowind?

Were you asking for a pirated copy? Because we don't condone that here.

**Comment by Alam188** [comment]
I am from Venezuela and here there are almost no video game stores, besides the economy is very bad. So I download the pirated games XD ... does the mod not work in a non-original version of the game?

**Comment by davidcernat** [comment]
Sorry, but we're going to end this right here.
