### ISSUE TITLE
Server behind cloudflare proxy with srv record

### ISSUE THREAD

**Issue by tompointexe** [TES3MP/TES3MP#575]
Hi, i'm looking for help to configure a server on my domain behing a cloudflare proxy
Thanks :)

**Comment by quexten** [comment]
The answer is a bit late, and the issue a bit out of scope of the project, so I guess this only helps people who encounter this in the future: Cloudflare, by default, only proxies HTTP traffic. If you want to proxy TES3MP, which communicates on a lower layer (UDP), then you would need something like Cloudflare spectrum (https://www.cloudflare.com/products/cloudflare-spectrum/), which is a paid service by Cloudflare. Though configuration is out of scope of this project.

If you just want to reach your tes3mp server via a domain, without a proxy, then create an A record or AAAA for IPv6 and point it to your server's IP.
