### ISSUE TITLE
MP Server List?

### ISSUE THREAD

**Issue by ich777** [TES3MP/TES3MP#576]
Is there anything special needed to make the server reachable from the Server Browser?

I forwarded both port 25565 UDP and 25560 UDP (also tried both ports with TCP) and the server shows up in the Server Browser but is listed as 'Unrachable'.
When I edit the file 'tes3mp-client-default.cfg' with my local or my public IP I can connect just fine to the server.

Am I missing something?

Also some tutorial say that you have to forward port 25560 but I really can't get the reason why I have to forward this port, can someone explain me for what it is and what if I want to change that to another port how I would do this or is it bound to the server port?

Here is a screenshot from the server start up:
![screenshot](https://user-images.githubusercontent.com/28066518/113511966-c175f980-9562-11eb-989e-df2b9139648d.png)

**Comment by davidcernat** [comment]
Have you tried reading the detailed FAQ linked to in the project readme?

https://github.com/TES3MP/openmw-tes3mp/blob/0.7.1/README.md

**Comment by ich777** [comment]
@davidcernat thanks for the speedy response. :)
Actually yes, but I've only read the first post.
In the FAQ it says that the server port needs to be forwarded TCP and UDP or am I wrong?

Okay, actually there are much tutorials out there that say that you have to open port 25565 and 25560 for whatever reason... :P
I think it would also be a option to add the basic port and needed protocol on the Github page since this is the source, just a suggestion. :)

Anyways, thank you very much!
