### ISSUE TITLE
[Bug] [breaking changes fix] navmesh updates is disabled when ai is off

### ISSUE THREAD

**Issue by Sarevalak** [TES3MP/TES3MP#580]
During the initialization of the game, the AI toggled off.
https://github.com/TES3MP/openmw-tes3mp/blob/ff10aa816b7c5edb82d3a513da9024c4f5039e57/apps/openmw/mwmp/Main.cpp#L164
And this commit (https://github.com/TES3MP/openmw-tes3mp/commit/c1ebd9474bdafb7c252428c83927802eac09b269) also disables navmesh updates when ai is turned off.
`Navigator` must be enabled to handle ai pathfinding properly.

**Comment by davidcernat** [comment]
The AI is turned on for the local authority in a particular cell. Pathfinding works just fine as a result. There are no breaking changes in that regard.

**Comment by davidcernat** [comment]
I've checked this carefully now and you're completely correct that the advanced pathfinding is turned off. Thanks for pointing out this other breaking change.

**Comment by davidcernat** [comment]
Solved by 63480a0012548e5653f06f9cb1cea420018571c2.
