### ISSUE TITLE
Mages Guild: Stolen Reports

### ISSUE THREAD

**Issue by Bizzle-Dapp** [TES3MP/TES3MP#582]
Quest works a charm, however if either report is placed on the ground (Works fine if placed in a container) then said report vanishes. 

Workaround was `player->additem "bk_Ajira1" 1` and `player->additem "bk_Ajira2" 1` in the interim. 

I took a brief look at the cell json and noticed a `deleted` attribute. I removed one of the values from this that aligned with the mushroom report however the report did not reappear. 

Can also confirm that the disappearing of the report is not bound to the Mages Guild cell either, as the report also vanished when placed on the floor just outside the Mages Guild in the Balmora cell also. 

EDIT!
I just relogged and the scroll has reappeared on the floor. Not sure how or why this happened. My friend reported a "noise" much like that of casting a self spell as he was stood next to the report.

**Comment by davidcernat** [comment]
It probably reappeared because of this:

> I removed one of the values from this that aligned with the mushroom report however the report did not reappear.

You had to rejoin for that change to have an effect.

**Comment by Bizzle-Dapp** [comment]
![26B9BFE7-694B-4945-9988-6CC8A377D677](https://user-images.githubusercontent.com/36421291/117350987-162fcb80-aea5-11eb-9153-9ff8ead3ee54.jpeg)
