### ISSUE TITLE
summons don't always summon correctly when you have an on-target buff on the same spell as the summon, leading to permanent summons.

### ISSUE THREAD

**Issue by EdgeLord69420911** [TES3MP/TES3MP#590]
I don't know if this happens in OpenMW or if it only happens in tes3mp, I haven't had a chance to properly test.

and it's too late now anyway, I'm going on permanent hiatus.
when I started experimenting with spells, I just wanted to know how the spellcrafting system worked; I wasn't expecting to find so many bugs.
between this and my inability to find or even afford a good therapist for my schizophrenia, OCD, and CPTSD, everything has become too stressful to the point that I can no longer function as a person.
it's not fun sending months at a time not being able to even turn on the computer or go outside without vomiting due to stress and anxiety; it's done a number on my teeth.
the whole entire reason I even started playing tes3mp was because at the time I naively thought I could somehow get over some of my mental health issues with it. 
it made sense at the time, seeing as the servers didn't have too many players at any given time.
I got way too far gone into the morrowind matrix, and it became literally the only thing I was able to talk or think about.
I spent around half a year documenting as much as I could because I had nothing else.
that was a lot of hard work, and I had something to show for it, at least until I deleted everything during a particularly bad mental breakdown.

p.s. I suggest that in the next version you should add a way for server owners to be able to modify the base cost of spell effects either via a script or through the files or something.

**Comment by davidcernat** [comment]
As far as I know, this is fixed in the work-in-progress version.

**Comment by datatypevoid** [comment]
> I don't know if this happens in OpenMW or if it only happens in tes3mp, I haven't had a chance to properly test.
> 
> and it's too late now anyway, I'm going on permanent hiatus.
> when I started experimenting with spells, I just wanted to know how the spellcrafting system worked; I wasn't expecting to find so many bugs.
> between this and my inability to find or even afford a good therapist for my schizophrenia, OCD, and CPTSD, everything has become too stressful to the point that I can no longer function as a person.
> it's not fun sending months at a time not being able to even turn on the computer or go outside without vomiting due to stress and anxiety; it's done a number on my teeth.
> the whole entire reason I even started playing tes3mp was because at the time I naively thought I could somehow get over some of my mental health issues with it.
> it made sense at the time, seeing as the servers didn't have too many players at any given time.
> I got way too far gone into the morrowind matrix, and it became literally the only thing I was able to talk or think about.
> I spent around half a year documenting as much as I could because I had nothing else.
> that was a lot of hard work, and I had something to show for it, at least until I deleted everything during a particularly bad mental breakdown.
> 
> p.s. I suggest that in the next version you should add a way for server owners to be able to modify the base cost of spell effects either via a script or through the files or something.

Almost this entire post is irrelevant to the project or contributors, why include your personal drama? What is the reasoning? Between the name and the content of the post, seems like low-effort trolling.
