### ISSUE TITLE
NPCs Failing Spellcasts

### ISSUE THREAD

**Issue by thezblah** [TES3MP/TES3MP#591]
Most NPCs appear to be rolling spell success and failing more often than not.  All NPCs listed here do not appear to have any chance of fumbling spells in singleplayer openMW and as a result many of these enemies are substantially easier to fight in tes3mp.

It appears that all npcs and creatures capable of producing spell effects are affected by this including:

Ash Slaves
Greater Bonewalker
Ancestral Ghost
Atronachs
Dremora
Ash Ghouls
Humanoid Spellcasters

This list is not exhaustive but what I've personally confirmed.

**Comment by davidcernat** [comment]
This is not relevant to the work-in-progress version.
