### ISSUE TITLE
0.8.0 client/server version mismatch out of the box

### ISSUE THREAD

**Issue by M6894** [TES3MP/TES3MP#598]
**The issue**
The client can not connect to the server provided from the same release (even locally). 
After the client is launched (either via browser or ./tes3mp) the message appears:

```
[ERR]: Version mismatch!
Your client is on version 0.8.0
Please make sure the server is on the same version.
```
Please note that the server starts with this compatible hash:
`Oldest compatible commit hash: 000e8724ca`
meanwhile the client starts with 
`Oldest compatible commit hash:  `

**Release in use**
[tes3mp-GNU+Linux-x86_64-release-0.8.0-abdaedd752-527229fab7.tar.gz](https://github.com/TES3MP/TES3MP/releases/download/tes3mp-0.8.0/tes3mp-GNU+Linux-x86_64-release-0.8.0-abdaedd752-527229fab7.tar.gz)
Commits up to the 16th of February as hotfixes.

**Example actions**
1. Download and unpack the release mentioned above
2. (optional) make some configurations in tes3mp-server-default.cfg and tes3mp-client-default.cfg
3. Start the server (./tes3mp-server) (server starts successfully)
4. Start the client (either via browser or ./tes3mp if password and IP are provided in tes3mp-client-default.cfg)
5. Client exits with the error mentioned above
6. Server is silent and running

Thank you in advance

**Comment by testman42** [comment]
Just tested, with a freshly downloaded package, could not replicate, local client connected to local server successfully.

Would you be so kind and download the release again? Firstly extract it into a new directory, so that you have a fresh, unmodified release, and then run server and client from there. That should work. If it does not, then something is really strange and I will ask you to provide more details about the machine that you are running TES3MP on.

**Comment by M6894** [comment]
@testman42 Thanks for your quick response. I just downloaded the release again and now it works as you supposed (with no configuration at all).
Then I also reverted all the changes i made to the previous installation of tes3mp (thanks to a backup of each file I changed available) and it is still not working.
So since the release was not changed, chances are it is me who is responsible for the issue and I am going to find out why.
Anyway since the new installation is fine, I will close the issue by the end of the day.

**Comment by testman42** [comment]
I believe that there were some hotfixes applied to the package after release, so there is a chance that the package you had was made before the hotfixes.
But still, that would only be an issue when you tried to connect to other servers. Getting versions mismatch with the server that was in same package as the client, that could happen only if you messed up with the version file or though some other fringe wizardry. Client and server in the same package should always be compatible.
In any case, I hope that things are working fine for you now.
If you encounter any further issues, do let us know.
