### ISSUE TITLE
client crashes when trying to steal from an npc's inventory. 0.8.0

### ISSUE THREAD

**Issue by pxsxs** [TES3MP/TES3MP#599]
the inventory opens, but when I press "take all" or drag from his inventory to mine, the game closes unexpectedly.

same on linux and windows
does not happen in openmw 0.47

**Comment by davidcernat** [comment]
The code for Take All and dragging is quite different. I have not been able to replicate the problem through dragging. The problem with Take All was, however, quite clear.

Can you check if everything is okay now after commit a95099cd03c1c6d21ab8bd450c536ec67d193f57?

**Comment by pxsxs** [comment]
you right, dragging is working.
I have not been able to compile successfully yet.

**Comment by davidcernat** [comment]
You don't have to compile it. Get the new hotfixed build that's here on GitHub.

**Comment by pxsxs** [comment]
solved!, thanks :)
