### ISSUE TITLE
Implement enchants

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#6]
_Originally posted by @Koncord_

**Comment by davidcernat** [comment]
For a long time, at Koncord's behest, this feature was supposed to only get added to the rewrite started in 2d0840cb3ab5b0d4f0d34c60f5d44789379ed192. With that rewrite not working out and being put on hold, I've gone ahead and added the feature to the pre-rewrite instead, primarily as part of b57807407afa8b1cb50026422c20278f73d56632, TES3MP/CoreScripts@426187a171a54ac74e1ca3a139549d694d459e86 and TES3MP/CoreScripts@9cd5dc8556b26a0524b10676067a14830bf79a86, and I'll be merging that same implementation into the rewrite – with the extensive necessary adjustments – when I have more time.
