### ISSUE TITLE
Running TES3MP server on an Raspberry PI [Discussion]

### ISSUE THREAD

**Issue by demosthenesk** [TES3MP/TES3MP#608]
Hello,
i have followed the wiki https://github.com/TES3MP/TES3MP/wiki/Running-TES3MP-server-on-an-Raspberry-PI for running server on RPI.

My question is, should i have to copy the *.esm files to server folder ? And if yes, in which path.

Thanks !!!

**Comment by demosthenesk** [comment]
Is there a TES3MP 0.8.0 for Raspberry-PI ?
Thanks !!!

**Comment by demosthenesk** [comment]
> My question is, should i have to copy the *.esm files to server folder ? And if yes, in which path.

I manage to run the server on a RPI. No need the esm files for the server.
I had to port forward the tcp/udp server port and now the server is reachable.

Now i need to wait for the 0.8.0 version of RPI.
Thanks !

**Comment by Patrix9999** [comment]
I've built the 0.8.0 version by my own.  
If someone is interested with using those, just grab the attached tar.gz archive
[tes3mp-server-GNU+Linux-armv7l-release-0.8.0--26756e6df9.tar.gz](https://github.com/TES3MP/TES3MP/files/8306316/tes3mp-server-GNU%2BLinux-armv7l-release-0.8.0--26756e6df9.tar.gz)

edit:
It's possible that you get version mismatch error while trying to connect with the server, in order to fix this, replace the resources/version file with the correct one (from client/game).

**Comment by demosthenesk** [comment]
> I've built the 0.8.0 version by my own. If someone is interested with using those, just grab the attached tar.gz archive [tes3mp-server-GNU+Linux-armv7l-release-0.8.0--26756e6df9.tar.gz](https://github.com/TES3MP/TES3MP/files/8306316/tes3mp-server-GNU%2BLinux-armv7l-release-0.8.0--26756e6df9.tar.gz)
> 
> @edit It's possible that you get version mismatch error while trying to connect with the server, in order to fix this, replace the resources/version file with the correct one (from client/game).

very nice my friend !!! Is there any howto you compiled the armv7l version ?
this is what i had need !!!

**Comment by demosthenesk** [comment]
Something else... after starting the server on RPI, how i stop it ?
I hit Ctrl+Z and it stops. But if i want to run it again i get these errors: Unknown bind__() error -1.

Loading server config from the package directory
Loading settings file: /home/pi/Documents/TES3MP-server/tes3mp-server-default.cfg
[2022-03-18 21:00:23] [INFO]: TES3MP dedicated server 0.8.0 (Linux  32-bit)
Protocol version: 9
Oldest compatible commit hash: 000e8724ca

[2022-03-18 21:00:23] [ERR]: [Script]: Could not find Lua CJSON! The decoding and encoding of JSON files will always use dkjson and be slower as a result.
Unknown bind__() error -1.
[2022-03-18 21:00:23] [ERR]: Failed to bind port. Make sure a server isn't already running on that port.
[2022-03-18 21:00:23] [ERR]: [Script]: Server crash from script error!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to bind port. Make sure a server isn't already running on that port.
./tes3mp-server: line 7:  5010 Aborted                 LD_LIBRARY_PATH="./lib" ./tes3mp-server.armv7l "$@"

A netstat -pal shows a udp bind on server port
udp        0      0 piwall:25565            0.0.0.0:*                           4852/./tes3mp-serve

sudo kill 4852 seems not killing the pid
why ? How i terminate the server correctly ?

**Comment by demosthenesk** [comment]
i manage to kill the server with
sudo killall -9 tes3mp-server

**Comment by demosthenesk** [comment]
I raise the Master Server rate to 60000, i think this value is in miliseconds... because considered this as spam and restarted my router continuously..

What does this value do exactly ?

**Comment by Patrix9999** [comment]
> 

I've used this awesome shell script to install all of the required dependencies and compile the server.
https://github.com/GrimKriegor/TES3MP-deploy

One thing to note, the server won't compile under gcc9 because of [this](https://github.com/TES3MP/TES3MP/issues/552) issue:
However, building with gcc-8 works perfectly fine.

**Comment by demosthenesk** [comment]
> > 
> 
> I've used this awesome shell script to install all of the required dependencies and compile the server. https://github.com/GrimKriegor/TES3MP-deploy
> 
> One thing to note, the server won't compile under gcc9 because of [this](https://github.com/TES3MP/TES3MP/issues/552) issue: However, building with gcc-8 works perfectly fine.

Very nice !!! Thank you for everything !!!

**Comment by demosthenesk** [comment]
i have written a bash script that works like a watchdog but for the server proccess.
if server goes down this script restart the server.

watch_TES3MP_SERVER.sh
```
#!/bin/bash

echo "Start watching proccess tes3mp-server..."
pid=$(pidof -s tes3mp-server)
sleep 2

if ! kill -0 $pid; then
    echo "#############################"
    echo "Process $pid doesn't exist."
    #start server
    echo "START Server..."
    nohup /home/pi/Documents/TES3MP-server/tes3mp-server
    pid=$(pidof -s tes3mp-server)
    echo "#############################"
#    exit 1
fi

while kill -0 $pid; do
    sleep 1
done

echo "#############################"
echo "Process $pid finished at $(date +"%F %T")."

echo "kill servers..."
#kill server
pkill -9 "tes3mp*"
#killall -9 tes3mp-server
#killall -9 tes3mp-server.armv7l

echo "Restart watching..."
nohup ./$0
echo "#############################"
```

Run it as a service:
tes3mp-server.service
```
[Unit]
Description=Run TES3MP Game Server
After=syslog.target network.target

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/home/pi/Documents/TES3MP-server/watch_TES3MP_SERVER.sh
ExecStop=killall -9 watch_TES3MP_SERVER.sh tes3mp-server tes3mp-server.armv7l

[Install]
WantedBy=multi-user.target
```

**Comment by testman42** [comment]
I would argue that checking out [tmux](https://github.com/tmux/tmux) (or GNU Screen) and learning basics of it makes working on Raspberry Pi or any other Linux server much easier and more efficient.

Before I was running TES3MP server from a Docker container which restarts on failure, I had this functionality implemented with  an infinite `while` loop running inside a tmux session. The loop would look like this in BASH: `while :; do ./tes3mp-server; done`.
But the downside of this was that it did not restart in case of a power outage or system reboot, while service and container can do that.
