### ISSUE TITLE
Cannot take items from corpse

### ISSUE THREAD

**Issue by MushiShirohime** [TES3MP/TES3MP#613]
I assume this is either an issue with Morrowind Rebirth (Seen the exact same issue on Reddit) and/or is because the item is enchanted and has lost charge.

`[2022-03-28 19:41:08] [INFO]: Received ID_CONTAINER from Mushi Shirohime
- action: 2
[2022-03-28 19:41:08] [INFO]: [Script]: Called "OnContainer" for Mushi Shirohime (1) and cell Odirnamat
[Script]: - packetOrigin was CLIENT_GAMEPLAY
[2022-03-28 19:41:08] [INFO]: [Script]: Saving Container from Mushi Shirohime (1) about Odirnamat
[Script]: - 283157-0, refId: orval llaren
[Script]: - Attempt to remove count of 1 from non-existent item glass jinkblade
- Finished processing ID_CONTAINER`

**Comment by davidcernat** [comment]
There was already a hotfix about this. Do you have it?

**Comment by MushiShirohime** [comment]
I am running the latest version of TES3MP 0.8.0 So unless it's a separate thing then I should have it?

**Comment by testman42** [comment]
Download TES3MP again and use that to check if the issue still happens in it.

**Comment by MushiShirohime** [comment]
@testman42 Dunno what was wrong with the initial download but this fixed it
Hopefully whatever caused it the first time doesn't happen again but I got a fix for if it does at least!
Thanks for the help!
