### ISSUE TITLE
Fails to start on Linux (missing dependency libzvbi?)

### ISSUE THREAD

**Issue by ja-cop** [TES3MP/TES3MP#614]
First of all, thanks for this awesome project! 

Not sure if this is a TES3MP or OpenMW issue. I'm using release tes3mp-GNU+Linux-x86_64-release-0.8.0-f219cb5417-6fdd31f3b9.tar.gz on Void Linux glibc edition.

---

I start `./openmw-launcher`, and the launcher starts fine. I click "Play" and it opens the server browser. I double click on my server, click "Connect", type in the password, and click "OK". At this point, the server browser closes but Morrowind does not start, and the log prints (immediately after all the pong responses):

```
QThread::start: Thread termination error (No such process)
Loading client config from the package directory
./tes3mp.x86_64: error while loading shared libraries: libzvbi.so.0: cannot open shared object file: No such file or directory
```

Is this library supposed to be bundled with the release, or installed by the user? If the latter, is it documented somewhere?

**Comment by demosthenesk** [comment]
Vertical Blanking Interval decoder (VBI)

The vertical blanking interval (VBI) is an interval in a television signal
that temporarily suspends transmission of the signal for the electron gun
to move back up to the first line of the television screen to trace the
next screen field.

in my ubuntu-mate 20.04 i have installed 
libzvbi-common
libzvbi0

**Comment by wloxyz** [comment]
I had the same issue on Void when trying to run the game. I worked around it by downloading / extracting Ubuntu's libzvbi0 deb package and moving `libzvbi.so.0` into TES3MP's `lib/` folder. Installation via xdeb didn't seem to put the file where it needed to be to be loaded by the program.

**Comment by ja-cop** [comment]
Thanks both, using Debian's libzvbi worked! I'll close this issue, but I would love to see a Flatpak release of this in the future as it would be properly portable across distros! :)
