### ISSUE TITLE
TE3MP VR: attempting to interact with the desktop in SteamVR doesn't work unless focus is manually broken

### ISSUE THREAD

**Issue by InconsolableCellist** [TES3MP/TES3MP#623]
Issue: Attempting to interact with the desktop doesn't work with SteamVR's desktop view unless you manually break focus from the game window using the physical keyboard or mouse.

Steps to reproduce:
1. Start TES3MP VR 0.8.1
2. Open SteamVR (small recessed Steam button on an Index controller)
3. Click the Desktop button to show the desktop
4. Attempt to interact with the desktop using the controllers

Observed behavior:
Clicks aren't registered on the desktop. If you change focus from the game window (by pressing the Windows key on a physical keyboard, alt-tab, or use the physical mouse, etc.) then you can interact with the desktop up until TES3MP VR gains focus again.

Expected behavior:
It's possible to change focus and interact with the desktop using SteamVR's desktop view, as you can with other games.

**Comment by davidcernat** [comment]
Do you get something similar in the OpenMW VR that was based on OpenMW 0.47? Do you still get it in later OpenMW VR builds? Or is it somehow specific to TES3MP VR?

**Comment by InconsolableCellist** [comment]
I can test to see if it's upstream. Do you have a link to the build that TES3MP VR is based off of? I only found https://gitlab.com/madsbuvi/openmw/-/releases and it's from an older Reddit guide.

**Comment by davidcernat** [comment]
Here's one that's very close:

https://www.reddit.com/r/OpenMWVR/comments/sr2caw/no_audio_and_black_screen/hwq2ktv/

**Comment by davidcernat** [comment]
Anyway, I'm pretty sure this is something for OpenMW VR to deal with.
