### ISSUE TITLE
TES3MP VR: Game window minimizes and restores when attempting to use a desktop interaction tool like OVR Toolkit

### ISSUE THREAD

**Issue by InconsolableCellist** [TES3MP/TES3MP#624]
Issue: Attempting to use the desktop while running TES3MP VR using OVR Toolkit results in the game window minimizing and restoring based on where the controllers are pointed. This makes interacting with the desktop very difficult. This issue may exist for Virtual Desktop and others, but I didn't test them. SteamVR's desktop view works if you can break focus from the game window (separate issue, #623)

Steps to reproduce: 
1. Launch TES3MP VR 0.8.1
2. Open OVR Toolkit (and possibly another desktop control program like Virtual Desktop). The default binding is to double-squeeze on both Index controller grips
3. Position the controller so that focus is pointed to the virtual desktop window

Observed behavior:
TES3MP VR will minimize itself as soon as the controller is pointed at the desktop. If your controller drifts and points back to the VR space (any area not covered by the virtual desktop overlay) TES3MP VR will restore itself back to its previous size and position.

Expected behavior:
TES3MP VR doesn't continuously minimize and restore itself, which makes using the desktop extremely difficult. It should be possible to change focus in the desktop and have the TES3MP window in the background, or optionally minimize it and keep it minimized.

Some games will actually change behavior a bit when focus is lost, like The Forest or maybe Pavlov will stop playing audio unless the window has focus. But none minimize and restore based on where the controllers are pointed.

Workaround:
Continuously point a controller at the desktop to keep TES3MP VR minimized while you're interacting with the desktop (which is difficult, cumbersome, and not required for any other VR game)

**Comment by davidcernat** [comment]
I'm confident this is an OpenMW VR matter, not a TES3MP matter. Try on the appropriate repo.
