### ISSUE TITLE
TES3MP VR feature request: quick access for spells/weapons/items without having to use a menu

### ISSUE THREAD

**Issue by InconsolableCellist** [TES3MP/TES3MP#625]
On a desktop it's possible to quickly change between the 10 quick menu items in OpenMW/TES3MP, but in VR (TES3MP VR 0.8.1) there doesn't seem to be a way to do this. It'd be nice if there could be a new mechanic for quickly changing between those items from within VR, which is pretty important when in a battle that you can't pause. Perhaps something like holding down the right trackpad and moving your hand in one of 8 cardinal directions to draw an item from one of 8 slots?

**Comment by davidcernat** [comment]
Your issues aren't for TES3MP VR, they're for OpenMW VR (or at least the OpenMW VR that was based on OpenMW 0.47).

Opening up VR-related issues here that don't pertain to multiplayer is like opening up OpenMW issues here that don't pertain to multiplayer. You're on the wrong repo.
