### ISSUE TITLE
Crash when entering new cell.

### ISSUE THREAD

**Issue by Necromunger** [TES3MP/TES3MP#628]
[tes3mp-client-2022-07-04-21_36_43-crash.zip](https://github.com/TES3MP/TES3MP/files/9039483/tes3mp-client-2022-07-04-21_36_43-crash.zip)

I crashed while entering the "Bank" near vivic on the server "Nerevarine Prophecies".

Find both log and dump file in zip folder.

**Comment by davidcernat** [comment]
You can't replicate the crash by entering the cell again, right?

**Comment by Necromunger** [comment]
No, but I'm mostly reporting because I crash from various cell transitions extremely often. But not in any nicely reproducible way.
