### ISSUE TITLE
Can't join a server on a fresh installation

### ISSUE THREAD

**Issue by FN-57x28mm** [TES3MP/TES3MP#630]
This is the first time i've installed and attempted to use TES3MP, and upon completing the installation, I attempted to join an empty server to test that it's working or not. Whenever I find and try to join a compatible server, using the same content packs (currently I only have the default Tribunal and Bloodmoon selected), I get this error message and the browser closes immediately after:
![image](https://user-images.githubusercontent.com/42077032/188207849-41d99d7b-67b5-449f-a51c-2c3559541184.png)
I'm not attempting to run openMW VR, and I'm not sure what the rest means. Can someone help?

**Comment by davidcernat** [comment]
You are, in fact, trying to run TES3MP VR instead of the regular TES3MP client. Read the release description again:

https://i.imgur.com/fF5oHgi.jpg
