### ISSUE TITLE
Crashing after making character

### ISSUE THREAD

**Issue by C0mputerPyr0** [TES3MP/TES3MP#633]
My friend is able to initially connect to my server, but immediately after character creation, his game get's a fatal error and just calls out to read the crash dump file. The thing is, my friend is able to load in perfectly fine and play the game on my server from it, and I have had multiple other people load in successfully as well. It's just my first friends desktop that is getting this issue.
[tes3mp-client-2022-09-27-02_21_00-crash.zip](https://github.com/TES3MP/TES3MP/files/9653003/tes3mp-client-2022-09-27-02_21_00-crash.zip)

**Comment by davidcernat** [comment]
The crash is happening in atio6axx.dll.

In other words, it's the exact same problem that these people were having:

https://www.reddit.com/r/tes3mp/comments/wr9k8g/i_crash_on_character_creation/ikuvf0l/
https://www.reddit.com/r/tes3mp/comments/x50ijh/crash_after_character_creation/incu7cr/
