### ISSUE TITLE
Invalid server password does not terminate connection.

### ISSUE THREAD

**Issue by SoupySoups** [TES3MP/TES3MP#637]
When receiving the "ID_INVALID_PASSWORD" packet (0x18) in tes3mp 0.8.1, the server does not disconnect the connection, instead leaving it up to the client to disconnect. Potentially an issue if an older version of the client with a vulnerability, modified to ignore the packet connects to a server.

**Comment by SoupySoups** [comment]
I mean it should according to rakpeer.cpp, but data is still sent 
https://github.com/facebookarchive/RakNet/blob/1a169895a900c9fc4841c556e16514182b75faf8/Source/RakPeer.cpp#:~:text=()%2C%200)%3B-,remoteSystem%2D%3EconnectMode%3DRemoteSystemStruct%3A%3ADISCONNECT_ASAP_SILENTLY%3B,-return%3B

**Comment by SoupySoups** [comment]
sorry nvm had wrong settings

**Comment by davidcernat** [comment]
What
