### ISSUE TITLE
Crashes when i launch tes3mp.exe

### ISSUE THREAD

**Issue by tmachgaming** [TES3MP/TES3MP#638]
it was working fine but i tabbed out and my pc crashed after i restarted my pc tes3mp crashes when i launch it 
[tes3mp-client-2023-01-11-04_56_10.log](https://github.com/TES3MP/TES3MP/files/10391592/tes3mp-client-2023-01-11-04_56_10.log)

**Comment by testman42** [comment]
Does OpenMW 0.47 run fine for you?
What GPU do you have in your PC?

**Comment by tmachgaming** [comment]
i have a amd 6700xt but i fixed it when it crashed the first time it disabled my gpu in device manager somehow

**Comment by tmachgaming** [comment]
after i re enabled it it works fine now
