### ISSUE TITLE
[request]Have a chat channel on a libre platform

### ISSUE THREAD

**Issue by tuxayo** [TES3MP/TES3MP#639]
Be it Matrix, XMPP or IRC or something else.

**Comment by datatypevoid** [comment]
Matrix would be excellant! Great suggestion!

**Comment by davidcernat** [comment]
We used to have Matrix and IRC channels that were bridged to Discord, but trolls kept using them to evade their Discord bans, so let's go with no for now.

**Comment by datatypevoid** [comment]
Poor excuse in my opinion.

**Comment by testman42** [comment]
There is TES3MP Matrix room, and also TES3MP IRC channel on libera.chat.

they are just not bridged to Discord.

**Comment by datatypevoid** [comment]
Ah, great -- thank you! That wasn't clear from the phrasing of Cernat's response.

**Comment by tuxayo** [comment]
@davidcernat 
> We used to have Matrix and IRC channels that were bridged to Discord, but trolls kept using them to evade their Discord bans, so let's go with no for now.

Can the TES3MP Matrix room, and also TES3MP IRC channel on libera.chat be advertised even as unofficial?
