### ISSUE TITLE
crash.zip

### ISSUE THREAD

**Issue by mymmakmuxo** [TES3MP/TES3MP#645]
[tes3mp-client-2023-04-16-11_43_56-crash.zip](https://github.com/TES3MP/TES3MP/files/11241217/tes3mp-client-2023-04-16-11_43_56-crash.zip)
[tes3mp-client-2023-04-16-18_22_23-crash.zip](https://github.com/TES3MP/TES3MP/files/11241930/tes3mp-client-2023-04-16-18_22_23-crash.zip)

**Comment by davidcernat** [comment]
You are not using an official release of TES3MP, so I can't do anything with these dump files because I don't have a matching .pdb file.
