### ISSUE TITLE
Fatal Error during Launch: "No graphics API supported by OpenMW VR is supported by the OpenXR runtime"

### ISSUE THREAD

**Issue by hdarb** [TES3MP/TES3MP#647]
Pretty much what the title says. Whenever I try to launch and join a server, I receive this error. I don't know where to find the dumps, but this reads like a specific error with a specific cause. Is there any obvious solution given the error itself?

**Comment by davidcernat** [comment]
I assume you are using the VR build by mistake. Try reading what the release description says?

**Comment by hdarb** [comment]
Wow, what a blunder on my part. After installing the Win64 version it's running beautifully. Thank you David for your help and all your hard work that went into making this classic a shareable experience. I hope you're doing well and the world blesses you in turn for bringing so much joy to so many people.
