### ISSUE TITLE
Container functions

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#7]
_Originally posted by @Koncord_

**Comment by Koncord** [comment]
I think it should be implemented partially on the CPP and partially on Lua

**Comment by Koncord** [comment]
When players opening containers, they should send to server special flag for preventing race condition when 2 players editing the same container.

**Comment by Koncord** [comment]
And after closing container, they should send modified container to the server.

**Comment by Koncord** [comment]
This involves adding new callbacks: OnPlayerOpenContainer, OnPlayerCloseContainer

**Comment by Koncord** [comment]
Added hooks by 9ca206dda90e9a5b0ae75d790b2f9258ba853463

**Comment by Koncord** [comment]
- [ ] string GetItemName (int refid, int index)&emsp;&emsp;***should return empty if index is not exists***
- [ ] int GetItemCount (int refid, int index)
- [ ] int GetItemHealth (int refid, int index)
- [ ] void AddItem (int refid, string itemid)
- [ ] int SearchItem (int refid, string itemid)&emsp;&emsp;&emsp;***return index of item***

**Comment by davidcernat** [comment]
Implemented as of now, although SearchItem() does not exist and would not be particularly useful anyway.
