### ISSUE TITLE
Strange position sync issue

### ISSUE THREAD

**Issue by testman42** [TES3MP/TES3MP#77]
When tested on local instance (Linux Mint 18 x86_64, [2 clients 1 server](http://i3.kym-cdn.com/photos/images/original/000/199/770/415554.png)) at some point characters start teleporting around very quickly and CPU usage skyrockets.
Video and logs here:
https://drive.google.com/drive/folders/0B8JUDh0cBh4Tc2Zad2ZpMldYbGM?usp=sharing

**Comment by davidcernat** [comment]
As messed up as that looked, it seemed to fix itself just fine at the end... We call it "Eastern European hax."

**Comment by davidcernat** [comment]
Arguably fixed by 1f747d4375f1818be051692b71aa6aee0e41a6e5
