### ISSUE TITLE
Server console stops displaying messages from C++ logger

### ISSUE THREAD

**Issue by davidcernat** [TES3MP/TES3MP#92]
Sometimes, after a player logs in, the server console no longer displays any LOG_MESSAGE_SIMPLE or LOG_APPEND messages. However, print statements from Lua scripts still work correctly.

Regardless, this makes it impossible to debug server issues properly.

**Comment by Koncord** [comment]
Maybe logs are buffered. You should force flush buffer.

**Comment by davidcernat** [comment]
Why does it only ever happen right after a player logs in, though?

**Comment by Koncord** [comment]
f5f1a29f31505ee09749dec9d2c2109edcb814b6 may fix this issue.

**Comment by davidcernat** [comment]
This issue still exists, as can be seen here:

![](https://i.sli.mg/bgJgou.png)

**Comment by davidcernat** [comment]
Fixed by 174937f412075044de4efc7859fc9134c0422ad7 and TES3MP/PluginExamples@e698460845d56678dbc4334b0313b6104adf0c7f
